steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/cn-app-image:r130', '-f', 'docker/go/Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cn-app-image:r130']
images:
- 'gcr.io/$PROJECT_ID/cn-app-image:r130'