apiVersion: v1
kind: Service
metadata:
  name: cnweb-app
  labels:
    app: cnweb-app
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30080
    name: http
  selector:
    run: cnweb-app