<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
    <title>Chinese Notes: Chinese Font Design and Creation 中文笔记 - 汉字字体设计与创意</title>
    <link rel="shortcut icon" href="/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="styles.css"/>
    <meta name="keywords"
          content="Chinese Font Design and Creation 汉字字体设计与创意"/>
    <meta name="description"
          content="Chinese Font Design and Creation 汉字字体设计与创意"/>
    <script type="text/javascript" src="script/chinesenotes.js"></script>
  </head>
  <body>
    <div><span id="toolTip"><span id="pinyinSpan">Pinyin</span> <span id="englishSpan">English</span></span></div>
    <div class="breadcrumbs">
      <a href="index.html">Chinese Notes 中文笔记</a> &gt; 
      <a href="developers.php">Developers 计算机科学</a> &gt; 
      <a href="chinese_fonts.php">Chinese Fonts 汉字字体</a> &gt; 
      <a href="chinese_fonts_yanqin.php">Scans 扫描</a> &gt; 
      Yan Qin Ceremony Inscription 颜勤礼碑
    </div>      
    <h1 class='article'>Chinese Fonts 汉字字体</h1>
    <div class="box">
      <div class='fright'>
        <form action='/word_detail.php' method='post'>
          <div>
	      <input type='text' name='word' size='50'/>
          <input id='searchButton' type='submit' value='搜索 Search' title='搜索 Sōusuǒ Search'/>
          </div>
        </form>
      </div>
      <div class="prevNext">
        <a href="chinese_fonts_ref.php">Previous</a> 
        <a href="chinese_fonts.php#contents">Contents</a> 
        <a href="chinese_fonts_jinwen_scans.php">Next</a> 
      </div>
      <h2 class='article'>
        <a name="inscription"></a>
        <a href='/word_detail.php?id=17253' onmouseover="showToolTip(this, '顏勤禮碑 Yán Qín Lǐ Bēi', 'Yan Qin Ceremony Inscription')" 
        onmouseout='hideToolTip()'>颜勤礼碑</a>
        Yan Family Ceremonial Inscription
      </h2>
      <p>
        This inscription was written by Yan Zhenqing <a href='/word_detail.php?id=7809' onmouseover="showToolTip(this, '顏真卿 Yán Zhēnqīng', 'Yan Zhenqing')" 
        onmouseout='hideToolTip()'>颜真卿</a> in 779 in regular script <a href='/word_detail.php?id=2599' onmouseover="showToolTip(this, '楷書 kǎishū​', 'regular script')" 
        onmouseout="hideToolTip()">楷书</a>.
        The inscription is in memory of Yan Zhenqing's forebears, in particular, his grandfather.
        Three of the four sides of the inscription are still remaining.
        It contains 39 lines with 38 characters on each line and 5 lines with 37 characters with a total of 1667 characters.
        It is 175×90×22 cm in size.
      </p>
      <ul>
        <li>
          <a href='/images/yanqin16.jpg'>Page I Scan</a>,
          <a href='/svg/yanqin16svg.svg'>SVG Trace</a>：
          <a href='/character_search.php?unicode=21517' onmouseover="showToolTip(this, 'míng ', 'name / rank / title / position')" onmouseout="hideToolTip()">名</a><a href='/character_search.php?unicode=32862' onmouseover="showToolTip(this, 'wén wèn 闻', 'to hear / to smell / to make known / news')" onmouseout="hideToolTip()">聞</a>。<a href='/character_search.php?unicode=19971' onmouseover="showToolTip(this, 'qī ', 'Seven')" onmouseout="hideToolTip()">七</a><a href='/character_search.php?unicode=29234' onmouseover="showToolTip(this, 'wèi wéi 为 為', 'do / handle / govern / act / be')" onmouseout="hideToolTip()">爲</a><a href='/character_search.php?unicode=25010' onmouseover="showToolTip(this, 'xiàn 宪', 'a constitution / a statute / a law')" onmouseout="hideToolTip()">憲</a><a href='/character_search.php?unicode=23448' onmouseover="showToolTip(this, 'guān', 'an official / a public servant')" onmouseout="hideToolTip()">官</a>，<a href='/character_search.php?unicode=20061' onmouseover="showToolTip(this, 'jiǔ', 'nine')" onmouseout="hideToolTip()">九</a><a href='/character_search.php?unicode=29234' onmouseover="showToolTip(this, 'wèi wéi 为 為', 'do / handle / govern / act / be')" onmouseout="hideToolTip()">爲</a><a href='/character_search.php?unicode=30465' onmouseover="showToolTip(this, 'shěng xiǎn xǐng', 'province / save / economize')" onmouseout="hideToolTip()">省</a><a href='/character_search.php?unicode=23448' onmouseover="showToolTip(this, 'guān', 'an official / a public servant')" onmouseout="hideToolTip()">官</a>，<a href='/character_search.php?unicode=33616' onmouseover="showToolTip(this, 'jiàn 薦', 'to repeat / to reoccur / to recommend')" onmouseout="hideToolTip()">荐</a><a href='/character_search.php?unicode=29234' onmouseover="showToolTip(this, 'wèi wéi 为 為', 'do / handle / govern / act / be')" onmouseout="hideToolTip()">爲</a><a href='/character_search.php?unicode=31680' onmouseover="showToolTip(this, 'jié', 'festival / section / segment / to economize / to save / a joint / to regulate / to restrain')" onmouseout="hideToolTip()">節</a><a href='/character_search.php?unicode=24230' onmouseover="showToolTip(this, 'dù duó', 'capacity / degree / standard / to estimate / to cross / to ferry over')" onmouseout="hideToolTip()">度</a><a href='/character_search.php?unicode=25505' onmouseover="showToolTip(this, 'cǎi', 'to gather / to collect / to pick / to select')" onmouseout="hideToolTip()">採</a>
        </li>
        <li>
          <a href='/images/yanqin15.jpg'>Page II Scan</a>
          <a href='/svg/yanqin15svg.svg'>SVG Trace</a>：
          <a href='/character_search.php?unicode=35370' onmouseover="showToolTip(this, 'fǎng 访', 'to visit / to ask / to inquire')" onmouseout="hideToolTip()">訪</a><a href='/character_search.php?unicode=35264' onmouseover="showToolTip(this, 'guān guàn 覌 观', 'to see / to observe / to view / appearance')" onmouseout="hideToolTip()">觀</a><a href='/character_search.php?unicode=23519' onmouseover="showToolTip(this, 'chá', 'examine / investigate / notice')" onmouseout="hideToolTip()">察</a><a href='/character_search.php?unicode=20351' onmouseover="showToolTip(this, 'shǐ shì', 'to cause / send on a mission / to order / an envoy / a messenger / an ambassador')" onmouseout="hideToolTip()">使</a>，<a href='/character_search.php?unicode=39791' onmouseover="showToolTip(this, 'lǔ lǚ 鲁', 'foolish / stupid / rash / vulgar')" onmouseout="hideToolTip()">魯</a><a href='/character_search.php?unicode=37089' onmouseover="showToolTip(this, 'jùn', 'an administrative division')" onmouseout="hideToolTip()">郡</a><a href='/character_search.php?unicode=20844' onmouseover="showToolTip(this, 'gōng', 'fair / equitable / public / duke')" onmouseout="hideToolTip()">公</a>。<a href='/character_search.php?unicode=20801' onmouseover="showToolTip(this, 'yǔn', 'to grant / to allow / to consent')" onmouseout="hideToolTip()">允 </a><a href='/character_search.php?unicode=33255' onmouseover="showToolTip(this, 'zāng cáng zàng záng', 'good / right / generous / command')" onmouseout="hideToolTip()">臧</a>，<a href='/character_search.php?unicode=25958' onmouseover="showToolTip(this, 'dūn duì diāo duī tuán tún', 'esteem / honest / candid / sincere')" onmouseout="hideToolTip()">敦</a><a href='/character_search.php?unicode=23526' onmouseover="showToolTip(this, 'shí', 'real / true / solid / honest')" onmouseout="hideToolTip()">實</a><a href='/character_search.php?unicode=26377' onmouseover="showToolTip(this, 'yǒu yòu', 'have / own / possess / exist')" onmouseout="hideToolTip()">有</a><a href='/character_search.php?unicode=21519' onmouseover="showToolTip(this, 'lì', 'a government official / a magistrate')" onmouseout="hideToolTip()">吏</a><a href='/character_search.php?unicode=33021' onmouseover="showToolTip(this, 'néng nài tái tài nái xióng', 'to be able / can / ability')" onmouseout="hideToolTip()">能</a>，<a href='/character_search.php?unicode=33289' onmouseover="showToolTip(this, 'jǔ 举', 'raise / lift up / recommend')" onmouseout="hideToolTip()">舉</a>
        </li>
        <li>
          <a href='/images/yanqin14.jpg'>Page III Scan</a>,
          <a href='/svg/yanqin14svg.svg'>SVG Trace</a>：
          <a href='/character_search.php?unicode=32291' onmouseover="showToolTip(this, 'xiàn xuán 县', 'county / district / subdivision')" onmouseout="hideToolTip()">縣</a><a href='/character_search.php?unicode=20196' onmouseover="showToolTip(this, 'lìng líng lǐng', 'command / order / commandant / magistrate / allow / cause')" onmouseout="hideToolTip()">令</a>，<a href='/character_search.php?unicode=23472' onmouseover="showToolTip(this, 'zǎi', 'to slaughter / to rule')" onmouseout="hideToolTip()">宰</a><a href='/character_search.php?unicode=24310' onmouseover="showToolTip(this, 'yán', 'delay / postpone / defer')" onmouseout="hideToolTip()">延</a><a href='/character_search.php?unicode=26124' onmouseover="showToolTip(this, 'chāng', 'light from the sun / good / proper')" onmouseout="hideToolTip()">昌</a>。<a href='/character_search.php?unicode=22235' onmouseover="showToolTip(this, 'sì', 'four')" onmouseout="hideToolTip()">四</a><a href='/character_search.php?unicode=29234' onmouseover="showToolTip(this, 'wèi wéi 为 為', 'do / handle / govern / act / be')" onmouseout="hideToolTip()">爲</a><a href='/character_search.php?unicode=24481' onmouseover="showToolTip(this, 'yù 禦', 'to defend / to resist')" onmouseout="hideToolTip()">御</a><a href='/character_search.php?unicode=21490' onmouseover="showToolTip(this, 'shǐ', 'history / chronicle / annals')" onmouseout="hideToolTip()">史</a>，<a href='/character_search.php?unicode=20805' onmouseover="showToolTip(this, 'chōng', 'fill / be full / supply')" onmouseout="hideToolTip()">充</a><a href='/character_search.php?unicode=22826' onmouseover="showToolTip(this, 'tài', 'very / too / much / big / extreme')" onmouseout="hideToolTip()">太</a><a href='/character_search.php?unicode=23561' onmouseover="showToolTip(this, 'wèi​', 'a military officer')" onmouseout="hideToolTip()">尉</a><a href='/character_search.php?unicode=37101' onmouseover="showToolTip(this, 'guō guó', 'outer part of a city')" onmouseout="hideToolTip()">郭</a><a href='/character_search.php?unicode=23376' onmouseover="showToolTip(this, 'zǐ zi', 'offspring / child / fruit / seed of / 1st terrestrial branch')" onmouseout="hideToolTip()">子</a><a href='/character_search.php?unicode=20736' onmouseover="showToolTip(this, 'yí 仪', 'apparatus / rites / appearance / present / ceremony')" onmouseout="hideToolTip()">儀</a>
        </li>
        <li>
          <a href='/images/yanqin13.jpg'>Page IV Scan</a>,
          <a href='/svg/yanqin13svg.svg'>SVG Trace</a>：
          <a href='/character_search.php?unicode=21028' onmouseover="showToolTip(this, 'pàn', 'to judge / to discriminate / to conclude')" onmouseout="hideToolTip()">判</a><a href='/character_search.php?unicode=23448' onmouseover="showToolTip(this, 'guān', 'an official / a public servant')" onmouseout="hideToolTip()">官</a>、<a href='/character_search.php?unicode=27743' onmouseover="showToolTip(this, 'jiāng', 'river')" onmouseout="hideToolTip()">江</a><a href='/character_search.php?unicode=38517' onmouseover="showToolTip(this, 'líng', 'a hill / a mound / a mausoleum')" onmouseout="hideToolTip()">陵</a><a href='/character_search.php?unicode=23569' onmouseover="showToolTip(this, 'shǎo shào', 'few / less / inadequate')" onmouseout="hideToolTip()">少</a><a href='/character_search.php?unicode=23609' onmouseover="showToolTip(this, 'yǐn', 'govern / oversee / director')" onmouseout="hideToolTip()">尹</a>、<a href='/character_search.php?unicode=33606' onmouseover="showToolTip(this, 'jīng 荊', 'thorns / brambles / my wife / cane')" onmouseout="hideToolTip()">荆</a><a href='/character_search.php?unicode=21335' onmouseover="showToolTip(this, 'nán nā', 'south / southern part')" onmouseout="hideToolTip()">南</a><a href='/character_search.php?unicode=34892' onmouseover="showToolTip(this, 'xíng háng xìng hàng héng', 'go / walk / move / travel / circulate')" onmouseout="hideToolTip()">行</a><a href='/character_search.php?unicode=36557' onmouseover="showToolTip(this, 'jūn', 'army / military / soldiers / troops')" onmouseout="hideToolTip()">軍</a><a href='/character_search.php?unicode=21496' onmouseover="showToolTip(this, 'sī', 'to take charge of / to control / to manage / an officer')" onmouseout="hideToolTip()">司</a><a href='/character_search.php?unicode=39340' onmouseover="showToolTip(this, 'mǎ', 'horse / a surname')" onmouseout="hideToolTip()">馬</a>。<a href='/character_search.php?unicode=38263' onmouseover="showToolTip(this, 'cháng zhǎng zhàng 长', 'long / length / excel in / leader')" onmouseout="hideToolTip()">長</a><a href='/character_search.php?unicode=21375' onmouseover="showToolTip(this, 'qīng', 'noble / a high officer')" onmouseout="hideToolTip()">卿</a>、<a href='/character_search.php?unicode=26185' onmouseover="showToolTip(this, 'jìn 晋', 'to advance / to increase / to promote')" onmouseout="hideToolTip()">晉</a>
        </li>
        <li>
          <a href='/images/yanqin12.jpg'>Page V Scan</a>,
          <a href='/svg/yanqin12svg.svg'>SVG Trace</a>：
          <a href='/character_search.php?unicode=21375' onmouseover="showToolTip(this, 'qīng', 'noble / a high officer')" onmouseout="hideToolTip()">卿</a>、<a href='/character_search.php?unicode=37024' onmouseover="showToolTip(this, 'bīn', 'a county in Shaanxi province')" onmouseout="hideToolTip()">邠</a>、<a href='/character_search.php?unicode=20805' onmouseover="showToolTip(this, 'chōng', 'fill / be full / supply')" onmouseout="hideToolTip()">充</a><a href='/character_search.php?unicode=22283' onmouseover="showToolTip(this, 'guó 国', 'nation / country')" onmouseout="hideToolTip()">國</a>、<a href='/character_search.php?unicode=36074' onmouseover="showToolTip(this, 'zhì zhí 质', 'matter, material, substance')" onmouseout="hideToolTip()">質</a>、<a href='/character_search.php?unicode=22810' onmouseover="showToolTip(this, 'duō', 'much / many / more than / over')" onmouseout="hideToolTip()">多</a><a href='/character_search.php?unicode=28961' onmouseover="showToolTip(this, 'wú mó', 'negative / no / not / to lack / to have no')" onmouseout="hideToolTip()">無</a><a href='/character_search.php?unicode=31103' onmouseover="showToolTip(this, 'lù 禄', 'blessing / happiness / prosperity')" onmouseout="hideToolTip()">祿</a><a href='/character_search.php?unicode=26089' onmouseover="showToolTip(this, 'zǎo', 'early / soon / morning')" onmouseout="hideToolTip()">早</a><a href='/character_search.php?unicode=19990' onmouseover="showToolTip(this, 'shì', 'Generation / world / era')" onmouseout="hideToolTip()">世</a>。<a href='/character_search.php?unicode=21375' onmouseover="showToolTip(this, 'qīng', 'noble / a high officer')" onmouseout="hideToolTip()">卿</a>、<a href='/character_search.php?unicode=20508' onmouseover="showToolTip(this, 'tì', 'to raise high / unrestrained')" onmouseout="hideToolTip()">倜</a>、<a href='/character_search.php?unicode=20272' onmouseover="showToolTip(this, 'gū gǔ gù', 'merchant / estimate / guess / presume')" onmouseout="hideToolTip()">估</a>
        </li>
        <li>
          <a href='/images/yanqin11.jpg'>Page VI Scan</a>,
          <a href='/svg/yanqin11svg.svg'>SVG Trace</a>：
          <a href='/character_search.php?unicode=20235' onmouseover="showToolTip(this, 'jí', 'deceptive')" onmouseout="hideToolTip()">伋</a><a href='/character_search.php?unicode=20523' onmouseover="showToolTip(this, 'lún 伦', 'human relationship / order / coherence')" onmouseout="hideToolTip()">倫</a>，<a href='/character_search.php?unicode=20006' onmouseover="showToolTip(this, 'bìng bàng', 'Equal to / side by side / also / what is more / both')" onmouseout="hideToolTip()">並</a><a href='/character_search.php?unicode=29234' onmouseover="showToolTip(this, 'wèi wéi 为 為', 'do / handle / govern / act / be')" onmouseout="hideToolTip()">爲</a><a href='/character_search.php?unicode=27494' onmouseover="showToolTip(this, 'wǔ', 'military / martial')" onmouseout="hideToolTip()">武</a><a href='/character_search.php?unicode=23448' onmouseover="showToolTip(this, 'guān', 'an official / a public servant')" onmouseout="hideToolTip()">官</a>，<a href='/character_search.php?unicode=29572' onmouseover="showToolTip(this, 'xuán xuàn', 'deep / profound / abstruse')" onmouseout="hideToolTip()">玄</a><a href='/character_search.php?unicode=23403' onmouseover="showToolTip(this, 'sūn xùn', 'grandchild / descendent / surname')" onmouseout="hideToolTip()">孫</a><a href='/character_search.php?unicode=32024' onmouseover="showToolTip(this, 'hóng 纮', 'vast / expansive / a string / a ribbon')" onmouseout="hideToolTip()">紘</a>，<a href='/character_search.php?unicode=36890' onmouseover="showToolTip(this, 'tōng', 'to go through / to open / to connect / to know well / a supernatural power')" onmouseout="hideToolTip()">通</a><a href='/character_search.php?unicode=32681' onmouseover="showToolTip(this, 'yì 义', 'right conduct  righteousness')" onmouseout="hideToolTip()">義</a><a href='/character_search.php?unicode=23561' onmouseover="showToolTip(this, 'wèi​', 'a military officer')" onmouseout="hideToolTip()">尉</a>，<a href='/character_search.php?unicode=27794' onmouseover="showToolTip(this, 'méi mò', 'have not / not / to end / to die / to inundate')" onmouseout="hideToolTip()">沒</a><a href='/character_search.php?unicode=20110' onmouseover="showToolTip(this, 'yú xū', 'in / on / at / go to')" onmouseout="hideToolTip()">于</a><a href='/character_search.php?unicode=34875' onmouseover="showToolTip(this, 'mán', 'barbarian / bully')" onmouseout="hideToolTip()">蠻</a>
        </li>
        <li>
          <a href='/images/yanqin10.jpg'>Page VII Scan</a>,
          <a href='/svg/yanqin10svg.svg'>SVG Trace</a>：
          <a href='/character_search.php?unicode=27849' onmouseover="showToolTip(this, 'quán', 'fountain / spring')" onmouseout="hideToolTip()">泉</a><a href='/character_search.php?unicode=26393' onmouseover="showToolTip(this, 'míng 明', 'bright / clear / intelligent / light / brilliant / to understand / to illustrate')" onmouseout="hideToolTip()">朙</a>，<a href='/character_search.php?unicode=23389' onmouseover="showToolTip(this, 'xiào', 'filial piety / obedience')" onmouseout="hideToolTip()">孝</a><a href='/character_search.php?unicode=32681' onmouseover="showToolTip(this, 'yì 义', 'right conduct  righteousness')" onmouseout="hideToolTip()">義</a><a href='/character_search.php?unicode=26377' onmouseover="showToolTip(this, 'yǒu yòu', 'have / own / possess / exist')" onmouseout="hideToolTip()">有</a><a href='/character_search.php?unicode=21519' onmouseover="showToolTip(this, 'lì', 'a government official / a magistrate')" onmouseout="hideToolTip()">吏</a><a href='/character_search.php?unicode=36947' onmouseover="showToolTip(this, 'dào dǎo', 'a path / a road / a street / a method / a way')" onmouseout="hideToolTip()">道</a>，<a href='/character_search.php?unicode=29238' onmouseover="showToolTip(this, 'fù fǔ', 'father')" onmouseout="hideToolTip()">父</a><a href='/character_search.php?unicode=38283' onmouseover="showToolTip(this, 'kāi', 'open / initiate / begin / start')" onmouseout="hideToolTip()">開</a><a href='/character_search.php?unicode=22303' onmouseover="showToolTip(this, 'tǔ', 'soil / earth / items made of earth')" onmouseout="hideToolTip()">土</a><a href='/character_search.php?unicode=38272' onmouseover="showToolTip(this, 'mén', 'gate / door / entrance / opening')" onmouseout="hideToolTip()">門</a><a href='/character_search.php?unicode=20304' onmouseover="showToolTip(this, 'zuǒ', 'assist / aid / second / subordinate')" onmouseout="hideToolTip()">佐</a><a href='/character_search.php?unicode=20854' onmouseover="showToolTip(this, 'qí jī', 'his / her / its / their / that')" onmouseout="hideToolTip()">其 </a><a href='/character_search.php?unicode=35584' onmouseover="showToolTip(this, 'móu 谋', 'to plan / to scheme')" onmouseout="hideToolTip()">謀</a><a href='/character_search.php?unicode=24429' onmouseover="showToolTip(this, 'péng', 'name of an ancient country / a surname')" onmouseout="hideToolTip()">彭</a>
        </li>
        <li>
          <a href='/images/yanqin09.jpg'>Page VIII Scan</a>,
          <a href='/svg/yanqin09svg.svg'>SVG Trace</a>：<a href='/word_detail.php?id=3118' onmouseover="showToolTip(this, 'zhōu', 'state')" onmouseout="hideToolTip()">州</a><a href='/word_detail.php?id=24463' onmouseover="showToolTip(this, '司馬 sīmǎ', 'official post of minister of war')" onmouseout="hideToolTip()">司马</a>。<a href='/word_detail.php?id=7188' onmouseover="showToolTip(this, 'wēi', 'power / might / prestige')" onmouseout="hideToolTip()">威</a><a href='/word_detail.php?id=3062' onmouseover="showToolTip(this, 'míng', 'clear / bright')" onmouseout="hideToolTip()">明</a>，<a href='/word_detail.php?id=24507' onmouseover="showToolTip(this, 'qióng​', 'a mound')" onmouseout="hideToolTip()">邛</a><a href='/word_detail.php?id=3118' onmouseover="showToolTip(this, 'zhōu', 'state')" onmouseout="hideToolTip()">州</a><a href='/word_detail.php?id=24463' onmouseover="showToolTip(this, '司馬 sīmǎ', 'official post of minister of war')" onmouseout="hideToolTip()">司马</a>。<a href='/word_detail.php?id=11719' onmouseover="showToolTip(this, 'jì​', 'season / period')" onmouseout="hideToolTip()">季</a><a href='/word_detail.php?id=3062' onmouseover="showToolTip(this, 'míng', 'clear / bright')" onmouseout="hideToolTip()">明</a>、<a href='/word_detail.php?id=3223' onmouseover="showToolTip(this, 'zǐ', 'child / son')" onmouseout="hideToolTip()">子</a><a href='/word_detail.php?id=3316' onmouseover="showToolTip(this, '乾 gàn', 'dry / clean')" onmouseout="hideToolTip()">干</a>、<a href='/word_detail.php?id=14299' onmouseover="showToolTip(this, 'pèi', 'copious / abundant')" onmouseout="hideToolTip()">沛</a>、<a href='/word_detail.php?id=22875' onmouseover="showToolTip(this, 'yì​', 'to assist / to be ready to fly / to respect')" 
          onmouseout="hideToolTip()">翊</a>（州司馬。威明，邛州司馬。季明、子幹、沛、翊）
        </li>
        <li>
          <a href='/images/yanqin08.jpg'>Page IX Scan</a>,
          <a href='/svg/yanqin08svg.svg'>SVG Trace</a>：<a href='/word_detail.php?id=7802' onmouseover="showToolTip(this, '顏 yán', 'color')" onmouseout="hideToolTip()">颜</a>，<a href='/word_detail.php?id=8783' onmouseover="showToolTip(this, 'quán', 'fountain / spring')" onmouseout="hideToolTip()">泉</a><a href='/word_detail.php?id=3062' onmouseover="showToolTip(this, 'míng', 'clear / bright')" onmouseout="hideToolTip()">明</a><a href='/word_detail.php?id=417' onmouseover="showToolTip(this, 'nán', 'male')" onmouseout="hideToolTip()">男</a><a href='/word_detail.php?id=8146' onmouseover="showToolTip(this, '誕 dàn', 'birth / birthday')" onmouseout="hideToolTip()">诞</a>，<a href='/word_detail.php?id=961' onmouseover="showToolTip(this, 'jí', 'to reach')" onmouseout="hideToolTip()">及</a><a href='/word_detail.php?id=4223' onmouseover="showToolTip(this, 'jūn', 'monarch / lord / gentleman / ruler')" onmouseout="hideToolTip()">君</a><a href='/word_detail.php?id=3044' onmouseover="showToolTip(this, 'wài', 'outside / in addition / foreign / external')" onmouseout="hideToolTip()">外</a><a href='/word_detail.php?id=4730' onmouseover="showToolTip(this, 'céng', 'once / already / former / previously')" onmouseout="hideToolTip()">曾</a><a href='/word_detail.php?id=2786' onmouseover="showToolTip(this, '孫 Sūn', 'Sun')" onmouseout="hideToolTip()">孙</a><a href='/word_detail.php?id=8506' onmouseover="showToolTip(this, '瀋 Shěn', 'Shen')" onmouseout="hideToolTip()">沈</a><a href='/word_detail.php?id=6368' onmouseover="showToolTip(this, 'yíng', 'full / filled / surplus')" onmouseout="hideToolTip()">盈</a>、<a href='/word_detail.php?id=6559' onmouseover="showToolTip(this, '盧 Lú', 'Lu')" onmouseout="hideToolTip()">卢</a><a href='/word_detail.php?id=24523' onmouseover="showToolTip(this, 'tì​', 'far')" onmouseout="hideToolTip()">逖</a>，<a href='/word_detail.php?id=346' onmouseover="showToolTip(this, '並 bì​ng', 'and / furthermore / also')" 
          onmouseout="hideToolTip()">并</a>（顏，泉明男誕，及君外曾孫沈盈、盧逖，並）
        </li>
        <li>
          <a href='/images/yanqin07.jpg'>Page X Scan</a>,
          <a href='/svg/yanqin07svg.svg'>SVG Trace</a>：<a href='/word_detail.php?id=372' onmouseover="showToolTip(this, '為 wèi', 'for / to')" onmouseout="hideToolTip()">为</a><a href='/word_detail.php?id=5032' onmouseover="showToolTip(this, 'nì​', 'contrary / opposite / backwards')" onmouseout="hideToolTip()">逆</a><a href='/word_detail.php?id=16680' onmouseover="showToolTip(this, '賊 zéi', 'thief')" onmouseout="hideToolTip()">贼</a><a href='/word_detail.php?id=383' onmouseover="showToolTip(this, 'suǒ', 'measure word for houses, small buildings and institutions')" onmouseout="hideToolTip()">所</a><a href='/word_detail.php?id=4550' onmouseover="showToolTip(this, 'hài', 'to do harm to / to cause trouble to')" onmouseout="hideToolTip()">害</a>，<a href='/word_detail.php?id=6116' onmouseover="showToolTip(this, 'jū​', 'entirely / without exception')" onmouseout="hideToolTip()">俱</a><a href='/word_detail.php?id=6411' onmouseover="showToolTip(this, '矇 mēng', 'to deceive / to cheat / to hoodwink / to knock unconscious')" onmouseout="hideToolTip()">蒙</a><a href='/word_detail.php?id=3435' onmouseover="showToolTip(this, '贈 zèng', 'to give')" onmouseout="hideToolTip()">赠</a><a href='/word_detail.php?id=305' onmouseover="showToolTip(this, 'wŭ', 'five')" onmouseout="hideToolTip()">五</a><a href='/word_detail.php?id=4356' onmouseover="showToolTip(this, 'pǐn', 'product / goods / grade / thing')" onmouseout="hideToolTip()">品</a><a href='/word_detail.php?id=1664' onmouseover="showToolTip(this, 'Jīng', 'Beijing')" onmouseout="hideToolTip()">京</a><a href='/word_detail.php?id=5760' onmouseover="showToolTip(this, 'guān', 'official / government / organ of body')" onmouseout="hideToolTip()">官</a>。<a href='/word_detail.php?id=24525' onmouseover="showToolTip(this, 'jùn', 'to deepen / to extract / to manage / ladle')" onmouseout="hideToolTip()">濬</a>，<a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" onmouseout="hideToolTip()">好</a><a href='/word_detail.php?id=1238' onmouseover="showToolTip(this, '屬 shǔ', 'to belong to / category / be subordinate to / to be born in the year of (one of the 12 animals)')" 
          onmouseout="hideToolTip()">属</a>（為逆賊所害，俱蒙贈五品京官。濬，好屬）
        </li>
        <li>
          <a href='/images/yanqin06.jpg'>Page XI Scan</a>,
          <a href='/svg/yanqin06svg.svg'>SVG Trace</a>：<a href='/word_detail.php?id=2475' onmouseover="showToolTip(this, 'wén', 'language / culture / writing')" onmouseout="hideToolTip()">文</a>。<a href='/word_detail.php?id=13074' onmouseover="showToolTip(this, '翹 qiào', 'to hold up')" onmouseout="hideToolTip()">翘</a>、<a href='/word_detail.php?id=2865' onmouseover="showToolTip(this, '華 Huà', 'Hua')" onmouseout="hideToolTip()">华</a>、<a href='/word_detail.php?id=914' onmouseover="showToolTip(this, 'zhèng', 'main / upright / straight')" onmouseout="hideToolTip()">正</a>，<<a href='/word_detail.php?id=2785' onmouseover="showToolTip(this, '嶽 Yuè', 'Yue')" onmouseout="hideToolTip()">岳</a><a href='/word_detail.php?id=2480' onmouseover="showToolTip(this, '頁 yè', 'page')" onmouseout="hideToolTip()">页</a>><a href='/word_detail.php?id=346' onmouseover="showToolTip(this, '並 bì​ng', 'and / furthermore / also')" onmouseout="hideToolTip()">并</a><a href='/word_detail.php?id=4681' onmouseover="showToolTip(this, 'zǎo', 'early / morning')" onmouseout="hideToolTip()">早</a><a href='/word_detail.php?id=8835' onmouseover="showToolTip(this, 'yāo', 'to die prematurely')" onmouseout="hideToolTip()">夭</a>。<a href='/word_detail.php?id=16548' onmouseover="showToolTip(this, '穎 yǐng', 'clever / gifted')" onmouseout="hideToolTip()">颖</a>，<a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" onmouseout="hideToolTip()">好</a><a href='/word_detail.php?id=305' onmouseover="showToolTip(this, 'wŭ', 'five')" onmouseout="hideToolTip()">五</a><a href='/word_detail.php?id=3512' onmouseover="showToolTip(this, 'yán', 'to speak / to say')" onmouseout="hideToolTip()">言</a>，<a href='/word_detail.php?id=24951' onmouseover="showToolTip(this, 'jiào', 'to collate / to scratch')" onmouseout="hideToolTip()">挍</a><a href='/word_detail.php?id=2543' onmouseover="showToolTip(this, '書 shū​', 'book')" onmouseout="hideToolTip()">书</a><a href='/word_detail.php?id=16550' onmouseover="showToolTip(this, 'láng', 'a minister / an official / a youth')" 
          onmouseout="hideToolTip()">郎</a>（文。翹、華、正，<嶽頁>並早夭。穎，好五言，挍書郎）
        </li>
        <li>
          <a href='/images/yanqin05.jpg'>Page XII Scan</a>,
          <a href='/svg/yanqin05svg.svg'>SVG Trace</a>：<a href='/word_detail.php?id=24527' onmouseover="showToolTip(this, '頲 tǐng', 'straight')" onmouseout="hideToolTip()">颋</a><a href='/word_detail.php?id=5481' onmouseover="showToolTip(this, 'rén', 'kernel')" onmouseout="hideToolTip()">仁</a><a href='/word_detail.php?id=16395' onmouseover="showToolTip(this, 'xiào', 'to be filial')" onmouseout="hideToolTip()">孝</a><a href='/word_detail.php?id=3382' onmouseover="showToolTip(this, 'fāng', 'square / quadrilateral / direction / one side')" onmouseout="hideToolTip()">方</a><a href='/word_detail.php?id=914' onmouseover="showToolTip(this, 'zhèng', 'main / upright / straight')" onmouseout="hideToolTip()">正</a>，<a href='/word_detail.php?id=3062' onmouseover="showToolTip(this, 'míng', 'clear / bright')" onmouseout="hideToolTip()">明</a><a href='/word_detail.php?id=1044' onmouseover="showToolTip(this, '經 jīng', 'to go through / to experience')" onmouseout="hideToolTip()">经</a><a href='/word_detail.php?id=1114' onmouseover="showToolTip(this, 'dà', 'big / huge / large / major')" onmouseout="hideToolTip()">大</a><a href='/word_detail.php?id=6701' onmouseover="showToolTip(this, 'lǐ', 'reason / logic / science / inner principle or structure')" onmouseout="hideToolTip()">理</a><a href='/word_detail.php?id=1088' onmouseover="showToolTip(this, 'sī', 'company')" onmouseout="hideToolTip()">司</a><a href='/word_detail.php?id=734' onmouseover="showToolTip(this, 'zhí', 'straight')" onmouseout="hideToolTip()">直</a>，<a href='/word_detail.php?id=9253' onmouseover="showToolTip(this, 'chōng', 'to fill / to satisfy / to fulfill / to substitute')" onmouseout="hideToolTip()">充</a><a href='/word_detail.php?id=3023' onmouseover="showToolTip(this, '張 zhāng', 'sheet')" onmouseout="hideToolTip()">张</a><a href='/word_detail.php?id=315' onmouseover="showToolTip(this, '萬 wàn', 'ten thousand')" onmouseout="hideToolTip()">万</a><a href='/word_detail.php?id=9037' onmouseover="showToolTip(this, '頃 qǐng', 'unit of area equal to 100 mu or 6.6667 hectacres')" 
          onmouseout="hideToolTip()">顷</a>（頲仁孝方 正，明經大理司直，充張萬頃）
        </li>
        <li>
          <a href='/images/yanqin04.jpg'>Page XIII Scan</a>,
          <a href='/svg/yanqin04svg.svg'>SVG Trace</a>：<a href='/word_detail.php?id=18463' onmouseover="showToolTip(this, '嶺南 Lǐngnán', 'Lingnan')" onmouseout="hideToolTip()">岭南</a><a href='/word_detail.php?id=1022' onmouseover="showToolTip(this, '營 yíng', 'to trade / to operate / to run / to manage')" onmouseout="hideToolTip()">营</a><a href='/word_detail.php?id=815' onmouseover="showToolTip(this, 'tián', 'field')" onmouseout="hideToolTip()">田</a><a href='/word_detail.php?id=24461' onmouseover="showToolTip(this, 'pàn guān', 'a magistrate / a judge')" onmouseout="hideToolTip()">判官</a>。<a href='/word_detail.php?id=19622' onmouseover="showToolTip(this, 'yǐ​', 'to be pleasing / in a respectful manner')" onmouseout="hideToolTip()">顗</a>，<a href='/word_detail.php?id=18744' onmouseover="showToolTip(this, '鳳翔 Fèngxiáng', 'Fengxiang')" onmouseout="hideToolTip()">凤翔</a><a href='/word_detail.php?id=14187' onmouseover="showToolTip(this, '參軍 cānjū​n', 'to join the army')" onmouseout="hideToolTip()">参军</a>。<a href='/word_detail.php?id=24528' onmouseover="showToolTip(this, 'yǐ​', 'to be pleasing / to be respectful')" onmouseout="hideToolTip()">頍</a>，<a href='/word_detail.php?id=3252' onmouseover="showToolTip(this, 'tōng', 'to go through / to open')" onmouseout="hideToolTip()">通</a><a href='/word_detail.php?id=16323' onmouseover="showToolTip(this, 'wù​', 'to comprehend')" onmouseout="hideToolTip()">悟</a><a href='/word_detail.php?id=6708' onmouseover="showToolTip(this, '頗 pō', 'rather / quite / considerably / oblique / inclined / slanting')" 
          onmouseout="hideToolTip()">颇</a>（嶺南營田判官。顗，鳳翔參軍。頍，通悟頗）
        </li>
        <li>
          <a href='/images/yanqin03.jpg'>Page XIV Scan</a>,
          <a href='/svg/yanqin03svg.svg'>SVG Trace</a>：
          <a href='/word_detail.php?id=3670' onmouseover="showToolTip(this, 'shàn', 'virtuous / benevolent / well-disposed')" onmouseout="hideToolTip()">善</a><a href='/word_detail.php?id=24971' onmouseover="showToolTip(this, '隷書 lì​shū​', 'clerical script')" onmouseout="hideToolTip()">隷书</a>，<a href='/word_detail.php?id=18249' onmouseover="showToolTip(this, 'tàizǐ', 'a prince')" onmouseout="hideToolTip()">太子</a><a href='/word_detail.php?id=6045' onmouseover="showToolTip(this, 'xǐ', 'to wash / to bathe')" onmouseout="hideToolTip()">洗</a><a href='/word_detail.php?id=2618' onmouseover="showToolTip(this, '馬 mǎ', 'horse')" onmouseout="hideToolTip()">马</a>、<a href='/word_detail.php?id=4762' onmouseover="showToolTip(this, '鄭 Zhèng', 'Zheng')" onmouseout="hideToolTip()">郑</a><a href='/word_detail.php?id=8459' onmouseover="showToolTip(this, 'wángfǔ', 'prince\'s mansion')" onmouseout="hideToolTip()">王府</a><a href='/word_detail.php?id=1088' onmouseover="showToolTip(this, 'sī', 'company')" onmouseout="hideToolTip()">司</a><a href='/word_detail.php?id=2618' onmouseover="showToolTip(this, '馬 mǎ', 'horse')" onmouseout="hideToolTip()">马</a>。<a href='/word_detail.php?id=346' onmouseover="showToolTip(this, '並 bì​ng', 'and / furthermore / also')" onmouseout="hideToolTip()">并</a><a href='/word_detail.php?id=10515' onmouseover="showToolTip(this, 'bùxíng', 'unfortunate / sad')" 
          onmouseout="hideToolTip()">不幸</a>（善隷書，太子洗馬、鄭王府司馬。並不幸）
        </li>
        <li>
          <a href='/images/yanqin02.jpg'>Page XV Scan</a>,
          <a href='/svg/yanqin02svg.svg'>SVG Trace</a>：
          <a href='/word_detail.php?id=2840' onmouseover="showToolTip(this, 'duǎn', 'short / lacking')" onmouseout="hideToolTip()">短</a><a href='/word_detail.php?id=4838' onmouseover="showToolTip(this, 'mì​ng', 'life')" onmouseout="hideToolTip()">命</a>。<a href='/word_detail.php?id=3252' onmouseover="showToolTip(this, 'tōng', 'to go through / to open')" onmouseout="hideToolTip()">通</a><a href='/word_detail.php?id=3062' onmouseover="showToolTip(this, 'míng', 'clear / bright')" onmouseout="hideToolTip()">明</a>，<a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" onmouseout="hideToolTip()">好</a><a href='/word_detail.php?id=1238' onmouseover="showToolTip(this, '屬 shǔ', 'to belong to / category / be subordinate to / to be born in the year of (one of the 12 animals)')" onmouseout="hideToolTip()">属</a><a href='/word_detail.php?id=2475' onmouseover="showToolTip(this, 'wén', 'language / culture / writing')" onmouseout="hideToolTip()">文</a>，<a href='/word_detail.php?id=501' onmouseover="showToolTip(this, '項 xiàng', 'an item / a thing')" onmouseout="hideToolTip()">项</a><a href='/word_detail.php?id=947' onmouseover="showToolTip(this, 'chéng', 'city')" onmouseout="hideToolTip()">城</a><a href='/word_detail.php?id=22424' onmouseover="showToolTip(this, 'wèi​', 'a military officer')" onmouseout="hideToolTip()">尉</a>。<a href='/word_detail.php?id=814' onmouseover="showToolTip(this, '歲 suì​', 'years old')" onmouseout="hideToolTip()">岁</a>，<a href='/word_detail.php?id=5653' onmouseover="showToolTip(this, '溫 wēn', 'warm / lukewarm')" onmouseout="hideToolTip()">温</a><a href='/word_detail.php?id=5248' onmouseover="showToolTip(this, 'jiāng', 'river')" onmouseout="hideToolTip()">江</a><a href='/word_detail.php?id=23773' onmouseover="showToolTip(this, 'chéng', 'a deputy')" onmouseout="hideToolTip()">丞</a>。<a href='/word_detail.php?id=24419' onmouseover="showToolTip(this, '覿 dí​', 'to face / to meet')" 
          onmouseout="hideToolTip()">觌</a>（短命。通明，好屬文，項城尉。歲，温江丞。覿）
        </li>
        <li>
          <a href='/images/yanqin01.jpg'>Page XVI Scan</a>,
          <a href='/svg/yanqin01svg.svg'>SVG Trace</a>：
          <a href='/word_detail.php?id=15438' onmouseover="showToolTip(this, '綿 mián', 'silk down')" onmouseout="hideToolTip()">绵</a><a href='/word_detail.php?id=3118' onmouseover="showToolTip(this, 'zhōu', 'state')" onmouseout="hideToolTip()">州</a><a href='/word_detail.php?id=14187' onmouseover="showToolTip(this, '參軍 cānjū​n', 'to join the army')" onmouseout="hideToolTip()">参军</a>。<a href='/word_detail.php?id=22400' onmouseover="showToolTip(this, '靚 jìng​', 'to make up (face)')" onmouseout="hideToolTip()">靓</a>，<a href='/word_detail.php?id=11119' onmouseover="showToolTip(this, '鹽 yán', 'salt')" onmouseout="hideToolTip()">盐</a><a href='/word_detail.php?id=9064' onmouseover="showToolTip(this, 'tíng', 'pavilion')" onmouseout="hideToolTip()">亭</a><a href='/word_detail.php?id=22424' onmouseover="showToolTip(this, 'wèi​', 'a military officer')" onmouseout="hideToolTip()">尉</a>。<a href='/word_detail.php?id=23294' onmouseover="showToolTip(this, '顥 hào', 'bright / white')" onmouseout="hideToolTip()">颢</a>，<a href='/word_detail.php?id=5481' onmouseover="showToolTip(this, 'rén', 'kernel')" onmouseout="hideToolTip()">仁</a><a href='/word_detail.php?id=387' onmouseover="showToolTip(this, 'hé', 'and')" onmouseout="hideToolTip()">和</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout="hideToolTip()">有</a><a href='/word_detail.php?id=3320' onmouseover="showToolTip(this, 'zhèng', 'politics / government')" onmouseout="hideToolTip()">政</a><a href='/word_detail.php?id=6701' onmouseover="showToolTip(this, 'lǐ', 'reason / logic / science / inner principle or structure')" onmouseout="hideToolTip()">理</a>，<a href='/word_detail.php?id=6027' onmouseover="showToolTip(this, 'Péng', 'Peng')" 
          onmouseout="hideToolTip()">蓬</a>（綿州參軍。靚，鹽亭尉。顥，仁和有政理，蓬）
        </li>
      </ul>
      <p>
        Source of scans: <span class='bookTitle'>Yan Family Ceremonial Inscription: Calligraphy Skills Lecture Series</span>
        [<a href='chinese_fonts_ref.php'>Bitian Jingnangu 2004</a>].
      </p>
      <p>
        All tracings are available under the 
        <a href='http://creativecommons.org/licenses/by/2.5/'>Creative Commons with Attribution 2.5</a> or later license with attribution to 
        <a href='http://chinesenotes.com'>chinesenotes.com</a>.
      </p>
      <div class="prevNext">
        <a href="chinese_fonts_ref.php">Previous</a> 
        <a href="chinese_fonts.php#contents">Contents</a> 
        <a href="chinese_fonts_jinwen_scans.php">Next</a> 
      </div>
    </div>
  </body>
</html>
