<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
    <title>Chinese Notes - Classical Chinese 汉语笔记 - 古文</title>
    <link rel="shortcut icon" href="/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="styles.css"/>
    <meta name="keywords"
          content="A web site for learning (Mandarin) Chinese. Classical Chinese 古文 Chinese English bilingual 双言"/>
    <meta name="description"
          content="Chinese Notes - Classical Chinese 汉语笔记 - 古文"/>
    <script type="text/javascript" src="script/chinesenotes.js"></script>
  </head>
  <body>
<?php
  	require_once 'ad_header.txt' ;
?>
    <div class="menubar">
      <a class='button' href='index.html'>Home - 首叶</a>
      <a class='button' href='tools.php'>Tools - 工具</a>
      <a class='button' href='articles.php'>Articles - 文章</a>
      <a class='button' href='culture.php'>Culture - 文化</a>
      <a class='button' href='reference.php'>Reference - 参考</a>
      <a class='selected' href='classics.php'>Classics - 古文</a>
      <a class='button' href='developers.php'>Developers - 软件</a>
     </div>
    <div class="breadcrumbs">
      <a href="index.html">Chinese Notes 中文笔记</a> &gt; 
      <a href="classics.php">Classics 古文</a> &gt; 
      <a href="classical_chinese.php">Introduction 古文入门</a> &gt; 
      Liu Xiang 刘向
    </div>      
    <h1 class='article'>古文入门 Introduction to Classical Chinese</h1>
    <div class="box">
      <div class='fright'>
        <form action='/word_detail.php' method='post'>
          <div>
	      <input type='text' name='word' size='50'/>
          <input id='searchButton' type='submit' value='搜索 Search' title='搜索 Sōusuǒ Search'/>
          </div>
        </form>
      </div>
      <div class="prevNext">
        <a href="classical_chinese_embedded.php">Previous</a> &nbsp;
        <a href="classical_chinese.php">Contents</a> &nbsp;
        <a href="classical_chinese_zhanguoce.php">Next</a>
      </div>
      <h2 class='article'>
        <a href='/word_detail.php?id=17363' onmouseover="showToolTip(this, 'Liú Xiàng', 'Liu Xiang')" onmouseout="hideToolTip()">刘向</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=4818' onmouseover="showToolTip(this, 'gùshi', 'narrative / story / tale')" onmouseout="hideToolTip()">故事</a>
        Stories by Liu Xiang
      </h2>
      <p>
        <a href='/word_detail.php?id=17363' onmouseover="showToolTip(this, 'Liú Xiàng', 'Liu Xiang')" onmouseout="hideToolTip()">刘向</a>
        Liu Xiang also known as 
        <a href='/word_detail.php?id=17413' onmouseover="showToolTip(this, 'Liú Gèngshēng', 'Liu Gengsheng')" onmouseout="hideToolTip()">刘更生</a>
        Liu Gengsheng and <a href='/word_detail.php?id=17414' onmouseover="showToolTip(this, 'Zǐ Zhèng', 'Zi Zheng')" onmouseout="hideToolTip()">子政</a>
        Zi Zheng was born in the city of <a href='/word_detail.php?id=17416' onmouseover="showToolTip(this, 'Péng Chéng', 'City of Peng')" onmouseout="hideToolTip()">彭城</a>
        Peng Cheng, now known as <a href='/word_detail.php?id=17415' onmouseover="showToolTip(this, 'Xúzhōu', 'Xuzhou')" onmouseout="hideToolTip()">徐州</a>
        Xuzhou, located in present day Jiangsu province.  He was a well know Confucian scholar and compiled
        <a href='/word_detail.php?id=17376' onmouseover="showToolTip(this, 'Xīn Xù', 'New Prefaces')" onmouseout="hideToolTip()">新序</a>
        New Prefaces, <a href='/word_detail.php?id=17362' onmouseover="showToolTip(this, 'Shuō Yuàn', 'Garden of Stories')" onmouseout="hideToolTip()">说苑</a>
        Garden of Stories, and
        <a href='/word_detail.php?id=17097' onmouseover="showToolTip(this, 'Zhàn Guó Cè', 'Stratagems of the Warring States')" onmouseout="hideToolTip()">战国策</a>
        Stratagems of the Warring States.
      </p>
      <h3 class='article'>
        <a name="text1"></a>
        <a href='/word_detail.php?id=17360' onmouseover="showToolTip(this, 'Jìn Píng Gōng', 'Duke Ping of Jin')" onmouseout="hideToolTip()">晋平公</a><a href='/word_detail.php?id=3723' onmouseover="showToolTip(this, 'wèn', 'to ask')" onmouseout="hideToolTip()">问</a><a href='/word_detail.php?id=1710' onmouseover="showToolTip(this, 'yú', 'in / at / to / from')" onmouseout="hideToolTip()">于</a><a href='/word_detail.php?id=17361' onmouseover="showToolTip(this, 'Shī Kuàng', 'Shi Kuang')" onmouseout="hideToolTip()">师旷</a>（<a href='/word_detail.php?id=17362' onmouseover="showToolTip(this, 'Shuō Yuàn', 'Garden of Stories')" onmouseout="hideToolTip()">说苑</a>）
        Duke Ping of Jin asks Shi Kuang (Garden of Stories)
      </h3>
      <div class='fright'>
        <a href='illustrations_use.php?mediumResolution=150px-Candleburning.jpg'><img class='use' 
           src='images/150px-Candleburning.jpg' alt='蜡烛 Candle' 
           title='蜡烛 Candle'/></a>
      </div>
      <p class='example'>
        <a href='/word_detail.php?id=17360' onmouseover="showToolTip(this, 'Jìn Píng Gōng', 'Duke Ping of Jin')" onmouseout="hideToolTip()">晋平公</a><a href='/word_detail.php?id=3723' onmouseover="showToolTip(this, 'wèn', 'to ask')" onmouseout="hideToolTip()">问</a><a href='/word_detail.php?id=1710' onmouseover="showToolTip(this, 'yú', 'in / at / to / from')" onmouseout="hideToolTip()">于</a><a href='/word_detail.php?id=17361' onmouseover="showToolTip(this, 'Shī Kuàng', 'Shi Kuang')" onmouseout="hideToolTip()">师旷</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout="hideToolTip()">曰</a><a href='/word_detail.php?id=17099' onmouseover="showToolTip(this, 'wú', 'I / my')" onmouseout="hideToolTip()">吾</a><a href='/word_detail.php?id=438' onmouseover="showToolTip(this, 'nián', 'year')" onmouseout="hideToolTip()">年</a><a href='/word_detail.php?id=307' onmouseover="showToolTip(this, 'qī', 'seven')" onmouseout="hideToolTip()">七</a><a href='/word_detail.php?id=310' onmouseover="showToolTip(this, 'shí', 'ten')" onmouseout="hideToolTip()">十</a>，<a href='/word_detail.php?id=3889' onmouseover="showToolTip(this, 'yù', 'desire')" onmouseout="hideToolTip()">欲</a><a href='/word_detail.php?id=3924' onmouseover="showToolTip(this, 'xué', 'to study / to learn')" onmouseout="hideToolTip()">学</a><a href='/word_detail.php?id=5084' onmouseover="showToolTip(this, 'kǒng', 'to be afraid / to be frightened / to fear')" onmouseout="hideToolTip()">恐</a><a href='/word_detail.php?id=1007' onmouseover="showToolTip(this, 'yǐ', 'already')" onmouseout="hideToolTip()">已</a><a href='/word_detail.php?id=16704' onmouseover="showToolTip(this, 'mù', 'evening / sunset')" onmouseout="hideToolTip()">暮</a><a href='/word_detail.php?id=8355' onmouseover="showToolTip(this, 'yǐ', 'final particle')" onmouseout="hideToolTip()">矣</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=17361' onmouseover="showToolTip(this, 'Shī Kuàng', 'Shi Kuang')" onmouseout="hideToolTip()">师旷</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout="hideToolTip()">曰</a><a href='/word_detail.php?id=17365' onmouseover="showToolTip(this, 'hé bù', 'why not')" onmouseout="hideToolTip()">何不</a><a href='/word_detail.php?id=17364' onmouseover="showToolTip(this, 'bǐng', 'to glean / to light up')" onmouseout="hideToolTip()">炳</a><a href='/word_detail.php?id=9954' onmouseover="showToolTip(this, 'zhú', 'candle')" onmouseout="hideToolTip()">烛</a><a href='/word_detail.php?id=3641' onmouseover="showToolTip(this, 'hū', 'expresses question or doubt')" onmouseout="hideToolTip()">乎</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=5363' onmouseover="showToolTip(this, 'Píng', 'Ping')" onmouseout='hideToolTip()'>平</a><a href='/word_detail.php?id=17359' onmouseover="showToolTip(this, 'gōng', 'duke')" onmouseout='hideToolTip()'>公</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=3908' onmouseover="showToolTip(this, 'ān', 'where / how why')" onmouseout='hideToolTip()'>安</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=12221' onmouseover="showToolTip(this, 'wéirén', 'behavior / conduct')" onmouseout='hideToolTip()'>为人</a><a href='/word_detail.php?id=6967' onmouseover="showToolTip(this, 'chén', 'statesman / vassal / courtier / minister / official')" onmouseout='hideToolTip()'>臣</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=3346' onmouseover="showToolTip(this, 'xì', 'drama / play / show')" onmouseout='hideToolTip()'>戏</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=4223' onmouseover="showToolTip(this, 'jūn', 'monarch / lord / gentleman / ruler')" onmouseout='hideToolTip()'>君</a><a href='/word_detail.php?id=3641' onmouseover="showToolTip(this, 'hū', 'expresses question or doubt')" onmouseout='hideToolTip()'>乎</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=6967' onmouseover="showToolTip(this, 'chén', 'statesman / vassal / courtier / minister / official')" onmouseout="hideToolTip()">臣</a><a href='/word_detail.php?id=3925' onmouseover="showToolTip(this, 'wén', 'to hear / sniff at / to smell')" onmouseout="hideToolTip()">闻</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout="hideToolTip()">之</a>，<br/>
        <a href='/word_detail.php?id=1451' onmouseover="showToolTip(this, 'shào', 'young')" onmouseout='hideToolTip()'>少</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" onmouseout='hideToolTip()'>好</a><a href='/word_detail.php?id=3924' onmouseover="showToolTip(this, 'xué', 'to study / to learn')" onmouseout='hideToolTip()'>学</a>，<a href='/word_detail.php?id=2566' onmouseover="showToolTip(this, 'rú', 'as (if) / such as / for example / to appear / to seem / to exceed')" onmouseout='hideToolTip()'>如</a><a href='/word_detail.php?id=17366' onmouseover="showToolTip(this, 'rì chū', 'sunrise')" onmouseout='hideToolTip()'>日出</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=3192' onmouseover="showToolTip(this, 'yáng', 'sun')" onmouseout='hideToolTip()'>阳</a>。<br/>
        <a href='/word_detail.php?id=5182' onmouseover="showToolTip(this, 'zhuàng', 'strong / robust / at one&apos;s prime')" onmouseout='hideToolTip()'>壮</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" onmouseout='hideToolTip()'>好</a><a href='/word_detail.php?id=3924' onmouseover="showToolTip(this, 'xué', 'to study / to learn')" onmouseout='hideToolTip()'>学</a>，<a href='/word_detail.php?id=2566' onmouseover="showToolTip(this, 'rú', 'as (if) / such as / for example / to appear / to seem / to exceed')" onmouseout='hideToolTip()'>如</a><a href='/word_detail.php?id=17367' onmouseover="showToolTip(this, 'rìzhōng', 'noon')" onmouseout='hideToolTip()'>日中</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=1229' onmouseover="showToolTip(this, 'guāng', 'light')" onmouseout='hideToolTip()'>光</a>。<br/>
        <a href='/word_detail.php?id=2835' onmouseover="showToolTip(this, 'lǎo', 'old')" onmouseout="hideToolTip()">老</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout="hideToolTip()">而</a><a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" onmouseout="hideToolTip()">好</a><a href='/word_detail.php?id=3924' onmouseover="showToolTip(this, 'xué', 'to study / to learn')" onmouseout="hideToolTip()">学</a>，<a href='/word_detail.php?id=2566' onmouseover="showToolTip(this, 'rú', 'as (if) / such as / for example / to appear / to seem / to exceed')" onmouseout="hideToolTip()">如</a><a href='/word_detail.php?id=17364' onmouseover="showToolTip(this, 'bǐng', 'to glean / to light up')" onmouseout="hideToolTip()">炳</a><a href='/word_detail.php?id=9954' onmouseover="showToolTip(this, 'zhú', 'candle')" onmouseout="hideToolTip()">烛</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=3062' onmouseover="showToolTip(this, 'míng', 'clear / bright')" onmouseout='hideToolTip()'>明</a>。<br/>
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=17364' onmouseover="showToolTip(this, 'bǐng', 'to glean / to light up')" onmouseout='hideToolTip()'>炳</a><a href='/word_detail.php?id=9954' onmouseover="showToolTip(this, 'zhú', 'candle')" onmouseout='hideToolTip()'>烛</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=3062' onmouseover="showToolTip(this, 'míng', 'clear / bright')" onmouseout='hideToolTip()'>明</a>，<a href='/word_detail.php?id=17370' onmouseover="showToolTip(this, 'shúyǔ', 'how can it be compared to')" onmouseout="hideToolTip()">熟与</a><a href='/word_detail.php?id=6894' onmouseover="showToolTip(this, 'mèi', 'dark')" onmouseout='hideToolTip()'>昧</a><a href='/word_detail.php?id=11499' onmouseover="showToolTip(this, 'xíng', 'to do')" onmouseout='hideToolTip()'>行</a><a href='/word_detail.php?id=3641' onmouseover="showToolTip(this, 'hū', 'expresses question or doubt')" onmouseout='hideToolTip()'>乎</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=5363' onmouseover="showToolTip(this, 'Píng', 'Ping')" onmouseout='hideToolTip()'>平</a><a href='/word_detail.php?id=17359' onmouseover="showToolTip(this, 'gōng', 'duke')" onmouseout='hideToolTip()'>公</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=3670' onmouseover="showToolTip(this, 'shàn', 'virtuous / benevolent / well-disposed')" onmouseout='hideToolTip()'>善</a><a href='/word_detail.php?id=6689' onmouseover="showToolTip(this, 'zāi', 'exclamatory or interrogative particle')" onmouseout='hideToolTip()'>哉</a>。
      </p>
      <p class='example'>
        Duke Ping of Jin said to Teacher Kuang, 'I am already seventy, I am afraid that my desire to study is already gone.'
      </p>
      <p class='example'>
        Teacher Kuang said, 'Why not light up the candle?'
      </p>
      <p class='example'>
        Duke Ping said, 'Why does the behavior of a servant mock his master?'
      </p>
      <p class='example'>
        The servant heard this:<br/>
        Study is good when young, like the sun at sunrise.<br/>
        Study is good in one's prime, like the light at noon.<br/>
        Study is good in one's old age, like the light from a candle.<br/>
      </p>
      <p class='example'>
        How would you not choose lighting a candle instead of walking in the darkness?
      </p>
      <p class='example'>
        Duke Ping said, 'Very virtuous.'
      </p>
      <p>
        <a href='/word_detail.php?id=17362' onmouseover="showToolTip(this, 'Shuō Yuàn', 'The Garden of Stories')" onmouseout="hideToolTip()">说苑</a>
        The Garden of Stories was written by 
        <a href='/word_detail.php?id=17363' onmouseover="showToolTip(this, 'Liú Xiàng', 'Liu Xiang')" onmouseout="hideToolTip()">刘向</a>
        Liu Xiang (79&mdash;8 BCE).  This style of story is a persuasion.  A persuasion is a story
        where the ruler asks a question and the advisor replies with a surprising answer.  The
        explanation of the surprising answer delivers a message. 
        <a href='/word_detail.php?id=17361' onmouseover="showToolTip(this, 'Shī Kuàng', 'Shi Kuang')" onmouseout='hideToolTip()'>师旷</a>
        was a well know musician from the time in Shanxi in present day 
        <a href='/word_detail.php?id=17371' onmouseover="showToolTip(this, 'Hóngdòng', 'Hongdong')" onmouseout="hideToolTip()">洪洞</a>
        Hongdong.
        This section is from 卷三 建本 Scroll 3 Building a Foundation.
        See [<a href='classical_chinese_references.php#reference'>LIU1</a>].
      </p>
      <h3 class='article'>
        <a name="snakes"></a>
        <a href='/word_detail.php?id=312' onmouseover="showToolTip(this, 'liǎng', 'two')" onmouseout="hideToolTip()">两</a><a href='/word_detail.php?id=3414' onmouseover="showToolTip(this, 'tóu', 'head')" onmouseout="hideToolTip()">头</a><a href='/word_detail.php?id=2617' onmouseover="showToolTip(this, 'shé', 'snake')" onmouseout="hideToolTip()">蛇</a>（<a href='/word_detail.php?id=17376' onmouseover="showToolTip(this, 'Xīn Xù', 'Xin Xu')" onmouseout="hideToolTip()">新序</a>）
        A Two Headed Snake (New Prefaces)
      </h3>
      <p class='example'>
        <a href='/word_detail.php?id=17378' onmouseover="showToolTip(this, 'Sūn Shū áo', 'Sun Shu ao')" onmouseout='hideToolTip()'>孙叔敖</a><a href='/word_detail.php?id=13414' onmouseover="showToolTip(this, 'wéi', 'to be')" onmouseout='hideToolTip()'>为</a><a href='/word_detail.php?id=13634' onmouseover="showToolTip(this, 'yīng ér', 'infant / baby')" onmouseout='hideToolTip()'>婴儿</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=524' onmouseover="showToolTip(this, 'shí', 'time / at that time')" onmouseout='hideToolTip()'>时</a>，<a href='/word_detail.php?id=275' onmouseover="showToolTip(this, 'chū', 'to go out')" onmouseout='hideToolTip()'>出</a><a href='/word_detail.php?id=4349' onmouseover="showToolTip(this, 'yóu', 'to walk / to tour / to roam / to travel')" onmouseout='hideToolTip()'>游</a>，<a href='/word_detail.php?id=2940' onmouseover="showToolTip(this, 'jiàn', 'to see / to meet')" onmouseout='hideToolTip()'>见</a><a href='/word_detail.php?id=312' onmouseover="showToolTip(this, 'liǎng', 'two')" onmouseout='hideToolTip()'>两</a><a href='/word_detail.php?id=3414' onmouseover="showToolTip(this, 'tóu', 'head')" onmouseout='hideToolTip()'>头</a><a href='/word_detail.php?id=2617' onmouseover="showToolTip(this, 'shé', 'snake')" onmouseout='hideToolTip()'>蛇</a>，<a href='/word_detail.php?id=2451' onmouseover="showToolTip(this, 'shā', 'to kill / to murder / to slaughter')" onmouseout='hideToolTip()'>杀</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=5534' onmouseover="showToolTip(this, 'mái', 'to bury')" onmouseout='hideToolTip()'>埋</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a>，<a href='/word_detail.php?id=5606' onmouseover="showToolTip(this, 'guī', 'to go back / to return')" onmouseout='hideToolTip()'>归</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=7133' onmouseover="showToolTip(this, 'qì', 'to sob')" onmouseout='hideToolTip()'>泣</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=4262' onmouseover="showToolTip(this, 'mǔ', 'mother')" onmouseout='hideToolTip()'>母</a><a href='/word_detail.php?id=3723' onmouseover="showToolTip(this, 'wèn', 'to ask')" onmouseout='hideToolTip()'>问</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=7115' onmouseover="showToolTip(this, 'gù', 'happening / instance / reason / cause')" onmouseout='hideToolTip()'>故</a>。
        <a href='/word_detail.php?id=9540' onmouseover="showToolTip(this, 'shū', 'uncle / father&apos;s younger brother')" onmouseout='hideToolTip()'>叔</a><a href='/word_detail.php?id=17377' onmouseover="showToolTip(this, 'áo', 'to ramble')" onmouseout='hideToolTip()'>敖</a><a href='/word_detail.php?id=1420' onmouseover="showToolTip(this, 'duì', 'to oppose / to face / to regard')" onmouseout='hideToolTip()'>对</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=3925' onmouseover="showToolTip(this, 'wén', 'to hear / sniff at / to smell')" onmouseout='hideToolTip()'>闻</a><a href='/word_detail.php?id=2940' onmouseover="showToolTip(this, 'jiàn', 'to see / to meet')" onmouseout='hideToolTip()'>见</a><a href='/word_detail.php?id=312' onmouseover="showToolTip(this, 'liǎng', 'two')" onmouseout='hideToolTip()'>两</a><a href='/word_detail.php?id=3414' onmouseover="showToolTip(this, 'tóu', 'head')" onmouseout='hideToolTip()'>头</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=2617' onmouseover="showToolTip(this, 'shé', 'snake')" onmouseout='hideToolTip()'>蛇</a><a href='/word_detail.php?id=17165' onmouseover="showToolTip(this, 'zhě', 'nominalizing function word')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=3880' onmouseover="showToolTip(this, 'sǐ', 'to die')" onmouseout='hideToolTip()'>死</a>。
        <a href='/word_detail.php?id=17213' onmouseover="showToolTip(this, 'xiàng', 'to face / to turn toward')" onmouseout="hideToolTip()">嚮</a><a href='/word_detail.php?id=17165' onmouseover="showToolTip(this, 'zhě', 'nominalizing function word')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=17099' onmouseover="showToolTip(this, 'wú', 'I / my')" onmouseout='hideToolTip()'>吾</a><a href='/word_detail.php?id=2940' onmouseover="showToolTip(this, 'jiàn', 'to see / to meet')" onmouseout='hideToolTip()'>见</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a>，<a href='/word_detail.php?id=5084' onmouseover="showToolTip(this, 'kǒng', 'to be afraid / to be frightened / to fear')" onmouseout='hideToolTip()'>恐</a><a href='/word_detail.php?id=343' onmouseover="showToolTip(this, 'qù', 'to go')" onmouseout='hideToolTip()'>去</a><a href='/word_detail.php?id=4262' onmouseover="showToolTip(this, 'mǔ', 'mother')" onmouseout='hideToolTip()'>母</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=3880' onmouseover="showToolTip(this, 'sǐ', 'to die')" onmouseout='hideToolTip()'>死</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" onmouseout='hideToolTip()'>也</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=4262' onmouseover="showToolTip(this, 'mǔ', 'mother')" onmouseout='hideToolTip()'>母</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=2617' onmouseover="showToolTip(this, 'shé', 'snake')" onmouseout='hideToolTip()'>蛇</a><a href='/word_detail.php?id=6691' onmouseover="showToolTip(this, 'jīn', 'today / modern / present / current / this / now')" onmouseout='hideToolTip()'>今</a><a href='/word_detail.php?id=3908' onmouseover="showToolTip(this, 'ān', 'where / how / why')" onmouseout='hideToolTip()'>安</a><a href='/word_detail.php?id=329' onmouseover="showToolTip(this, 'zài', 'at')" onmouseout='hideToolTip()'>在</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout="hideToolTip()">曰</a>，<a href='/word_detail.php?id=5084' onmouseover="showToolTip(this, 'kǒng', 'to be afraid / to be frightened / to fear')" onmouseout="hideToolTip()">恐</a><a href='/word_detail.php?id=2710' onmouseover="showToolTip(this, 'tārén', 'someone else / other people')" onmouseout="hideToolTip()">他人</a><a href='/word_detail.php?id=1632' onmouseover="showToolTip(this, 'yòu', 'again / also')" onmouseout="hideToolTip()">又</a><a href='/word_detail.php?id=2940' onmouseover="showToolTip(this, 'jiàn', 'to see / to meet')" onmouseout="hideToolTip()">见</a>，<a href='/word_detail.php?id=2451' onmouseover="showToolTip(this, 'shā', 'to kill / to murder / to slaughter')" onmouseout="hideToolTip()">杀</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout="hideToolTip()">而</a><a href='/word_detail.php?id=5534' onmouseover="showToolTip(this, 'mái', 'to bury')" onmouseout="hideToolTip()">埋</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout="hideToolTip()">之</a><a href='/word_detail.php?id=8355' onmouseover="showToolTip(this, 'yǐ', 'final particle')" onmouseout="hideToolTip()">矣</a>。
      </p>
      <p class='example'>
        <a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=4262' onmouseover="showToolTip(this, 'mǔ', 'mother')" onmouseout='hideToolTip()'>母</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=17099' onmouseover="showToolTip(this, 'wú', 'I / my')" onmouseout='hideToolTip()'>吾</a><a href='/word_detail.php?id=3925' onmouseover="showToolTip(this, 'wén', 'to hear / sniff at / to smell')" onmouseout='hideToolTip()'>闻</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=17379' onmouseover="showToolTip(this, 'yīndé', 'a hidden act of goodness')" onmouseout='hideToolTip()'>阴德</a><a href='/word_detail.php?id=17165' onmouseover="showToolTip(this, 'zhě', 'nominalizing function word')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=13325' onmouseover="showToolTip(this, 'tiān', 'heaven')" onmouseout='hideToolTip()'>天</a><a href='/word_detail.php?id=17380' onmouseover="showToolTip(this, 'bào', 'to repay')" onmouseout='hideToolTip()'>报</a><a href='/word_detail.php?id=650' onmouseover="showToolTip(this, 'yǐ', 'so as to')" onmouseout='hideToolTip()'>以</a><a href='/word_detail.php?id=2558' onmouseover="showToolTip(this, 'fú', 'good fortune / happiness / luck')" onmouseout='hideToolTip()'>福</a>，<a href='/word_detail.php?id=6690' onmouseover="showToolTip(this, 'rǔ', 'thou')" onmouseout='hideToolTip()'>汝</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout='hideToolTip()'>不</a><a href='/word_detail.php?id=3880' onmouseover="showToolTip(this, 'sǐ', 'to die')" onmouseout='hideToolTip()'>死</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" onmouseout='hideToolTip()'>也</a>。
        <a href='/word_detail.php?id=961' onmouseover="showToolTip(this, 'jí', 'to reach')" onmouseout='hideToolTip()'>及</a><a href='/word_detail.php?id=1323' onmouseover="showToolTip(this, 'zhǎng', 'to grow / to develop')" onmouseout='hideToolTip()'>长</a><a href='/word_detail.php?id=13412' onmouseover="showToolTip(this, 'wéi', 'to act as')" onmouseout='hideToolTip()'>为</a><a href='/word_detail.php?id=8445' onmouseover="showToolTip(this, 'Chǔ', 'state of Chu')" onmouseout='hideToolTip()'>楚</a><a href='/word_detail.php?id=17382' onmouseover="showToolTip(this, 'lìngyǐn', 'chief minister')" onmouseout='hideToolTip()'>令尹</a>，<a href='/word_detail.php?id=2188' onmouseover="showToolTip(this, 'wèi', 'not yet / did not / have not / not')" onmouseout='hideToolTip()'>未</a><a href='/word_detail.php?id=3440' onmouseover="showToolTip(this, 'zhì', 'to rule / to govern / to manage / to control')" onmouseout='hideToolTip()'>治</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=1075' onmouseover="showToolTip(this, 'guó', 'country')" onmouseout='hideToolTip()'>国</a><a href='/word_detail.php?id=399' onmouseover="showToolTip(this, 'rén', 'person / people')" onmouseout='hideToolTip()'>人</a><a href='/word_detail.php?id=3091' onmouseover="showToolTip(this, 'xìn', 'to believe')" onmouseout='hideToolTip()'>信</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=5482' onmouseover="showToolTip(this, 'rén', 'humane')" onmouseout='hideToolTip()'>仁</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" onmouseout='hideToolTip()'>也</a>。
      </p>
      <p class='example'>
        When Sun Shu ao was a young child he went out to play one time and saw a snake with two heads. 
        He killed and buried it then returned home and cried.
      </p>
      <p class='example'>
        His mother asked him what the reason was.
        Shu ao faced her and said, 'I saw a dead snake with two heads.
        I saw it facing me and was scared of dying so ran to mother.'
      </p>
      <p class='example'>
        His mother asked, 'Where is the snake now?'
      </p>
      <p class='example'>
        He said, 'I was afraid of other people seeing it, so I killed and buried it.'
      </p>
      <p class='example'>
        I sense a hidden good deed that heaven will repay with good luck.  You will not die.
        You will grow up to reach the level of chief minister of the State of Chu.  You will rule the people of the country with a belief in their humanity.
      </p>
      <h3 class='article'>
        <a name="zhaojianzi"></a>
        <a href='/word_detail.php?id=17404' onmouseover="showToolTip(this, 'Zhào Jiǎnzǐ', 'Zhao Jianzi')" onmouseout="hideToolTip()">赵简子</a><a href='/word_detail.php?id=3723' onmouseover="showToolTip(this, 'wèn', 'to ask')" onmouseout="hideToolTip()">问</a><a href='/word_detail.php?id=17405' onmouseover="showToolTip(this, 'Zǐ Gòng', 'Zi Gong')" onmouseout="hideToolTip()">子贡</a>（<a href='/word_detail.php?id=17362' onmouseover="showToolTip(this, 'Shuō Yuàn', 'Garden of Stories')" onmouseout="hideToolTip()">说苑</a>）
        Zhao Jianzi Asks Zi Gong (Garden of Stories)
      </h3>
      <p class='example'>
        <a href='/word_detail.php?id=17404' onmouseover="showToolTip(this, 'Zhào Jiǎnzǐ', 'Zhao Jianzi')" onmouseout="hideToolTip()">赵简子</a><a href='/word_detail.php?id=3723' onmouseover="showToolTip(this, 'wèn', 'to ask')" onmouseout="hideToolTip()">问</a><a href='/word_detail.php?id=17405' onmouseover="showToolTip(this, 'Zǐ Gòng', 'Zi Gong')" onmouseout="hideToolTip()">子贡</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout="hideToolTip()">曰</a>，<a href='/word_detail.php?id=7226' onmouseover="showToolTip(this, 'Kǒngzi', 'Confucius')" onmouseout="hideToolTip()">孔子</a><a href='/word_detail.php?id=12221' onmouseover="showToolTip(this, 'wéirén', 'behavior / conduct')" onmouseout="hideToolTip()">为人</a><a href='/word_detail.php?id=17186' onmouseover="showToolTip(this, 'hérú', 'what / how')" onmouseout="hideToolTip()">何如</a>。
        <a href='/word_detail.php?id=17405' onmouseover="showToolTip(this, 'Zǐ Gòng', 'Zi Gong')" onmouseout="hideToolTip()">子贡</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout="hideToolTip()">曰</a>，<a href='/word_detail.php?id=17407' onmouseover="showToolTip(this, 'yǎng', 'a martingale / discontented')" onmouseout="hideToolTip()">鞅</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=1263' onmouseover="showToolTip(this, 'néng', 'can / able')" onmouseout="hideToolTip()">能</a><a href='/word_detail.php?id=5058' onmouseover="showToolTip(this, 'shí', 'to know')" onmouseout='hideToolTip()'>识</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" onmouseout='hideToolTip()'>也</a>。
        <a href='/word_detail.php?id=6373' onmouseover="showToolTip(this, 'jiǎn', 'simple')" onmouseout="hideToolTip()">简</a><a href='/word_detail.php?id=3223' onmouseover="showToolTip(this, 'zǐ', 'child / son')" onmouseout="hideToolTip()">子</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=17117' onmouseover="showToolTip(this, 'yuè', 'to relax / to enjoy')" onmouseout='hideToolTip()'>说</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=3223' onmouseover="showToolTip(this, 'zǐ', 'child / son')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=1219' onmouseover="showToolTip(this, 'shì', 'matter / thing / item')" onmouseout='hideToolTip()'>事</a><a href='/word_detail.php?id=7226' onmouseover="showToolTip(this, 'Kǒngzi', 'Confucius')" onmouseout='hideToolTip()'>孔子</a><a href='/word_detail.php?id=2818' onmouseover="showToolTip(this, 'shǔ', 'to count')" onmouseout='hideToolTip()'>数</a><a href='/word_detail.php?id=310' onmouseover="showToolTip(this, 'shí', 'ten')" onmouseout='hideToolTip()'>十</a><a href='/word_detail.php?id=438' onmouseover="showToolTip(this, 'nián', 'year')" onmouseout='hideToolTip()'>年</a><a href='/word_detail.php?id=17409' onmouseover="showToolTip(this, 'zhōng', 'to complete / to finish')" onmouseout='hideToolTip()'>终</a><a href='/word_detail.php?id=17410' onmouseover="showToolTip(this, 'yè', 'training')" onmouseout='hideToolTip()'>业</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=343' onmouseover="showToolTip(this, 'qù', 'to go')" onmouseout='hideToolTip()'>去</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a>。
        <a href='/word_detail.php?id=17411' onmouseover="showToolTip(this, 'guǎ rén', 'the lone one / a ruler&apos;s way of refering to himself')" onmouseout='hideToolTip()'>寡人</a><a href='/word_detail.php?id=3723' onmouseover="showToolTip(this, 'wèn', 'to ask')" onmouseout='hideToolTip()'>问</a><a href='/word_detail.php?id=17151' onmouseover="showToolTip(this, 'zǐ', 'a polite form of address / master')" onmouseout='hideToolTip()'>子</a>，<a href='/word_detail.php?id=17151' onmouseover="showToolTip(this, 'zǐ', 'a polite form of address / master')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout='hideToolTip()'>不</a><a href='/word_detail.php?id=1263' onmouseover="showToolTip(this, 'néng', 'can / able')" onmouseout='hideToolTip()'>能</a><a href='/word_detail.php?id=5058' onmouseover="showToolTip(this, 'shí', 'to know')" onmouseout='hideToolTip()'>识</a>，<a href='/word_detail.php?id=3087' onmouseover="showToolTip(this, 'hé', 'what / how / why / which')" onmouseout='hideToolTip()'>何</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" onmouseout='hideToolTip()'>也</a>。
        <a href='/word_detail.php?id=17405' onmouseover="showToolTip(this, 'Zǐ Gòng', 'Zi Gong')" onmouseout='hideToolTip()'>子贡</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=8480' onmouseover="showToolTip(this, 'cì', 'to confer / to bestow / to grant')" onmouseout='hideToolTip()'>赐</a><a href='/word_detail.php?id=6901' onmouseover="showToolTip(this, 'pì', 'to give an example / to use as a metaphor')" onmouseout="hideToolTip()">譬</a><a href='/word_detail.php?id=7978' onmouseover="showToolTip(this, 'kě', 'thirsty')" onmouseout='hideToolTip()'>渴</a><a href='/word_detail.php?id=671' onmouseover="showToolTip(this, 'zhě', 'used after a verb to indicate a person who does the action')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=4358' onmouseover="showToolTip(this, 'yǐn', 'to drink')" onmouseout='hideToolTip()'>饮</a><a href='/word_detail.php?id=5248' onmouseover="showToolTip(this, 'jiāng', 'river')" onmouseout='hideToolTip()'>江</a><a href='/word_detail.php?id=3593' onmouseover="showToolTip(this, 'hǎi', 'sea / ocean')" onmouseout='hideToolTip()'>海</a>。
        <a href='/word_detail.php?id=3901' onmouseover="showToolTip(this, 'zhīzú', 'to be content')" onmouseout="hideToolTip()">知足</a><a href='/word_detail.php?id=14552' onmouseover="showToolTip(this, 'éryǐ', 'that is all')" onmouseout="hideToolTip()">而已</a>。
        <a href='/word_detail.php?id=7226' onmouseover="showToolTip(this, 'Kǒngzi', 'Confucius')" onmouseout='hideToolTip()'>孔子</a><a href='/word_detail.php?id=17115' onmouseover="showToolTip(this, 'yóu', 'to seem to be / is like')" onmouseout='hideToolTip()'>犹</a><a href='/word_detail.php?id=5248' onmouseover="showToolTip(this, 'jiāng', 'river')" onmouseout='hideToolTip()'>江</a><a href='/word_detail.php?id=3593' onmouseover="showToolTip(this, 'hǎi', 'sea / ocean')" onmouseout='hideToolTip()'>海</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" onmouseout='hideToolTip()'>也</a>，<a href='/word_detail.php?id=8480' onmouseover="showToolTip(this, 'cì', 'to confer / to bestow / to grant')" onmouseout='hideToolTip()'>赐</a><a href='/word_detail.php?id=1337' onmouseover="showToolTip(this, 'zé', 'expresses contrast with a previous sentence or clause')" onmouseout='hideToolTip()'>则</a><a href='/word_detail.php?id=17412' onmouseover="showToolTip(this, 'xī', 'what? / where? / why?')" onmouseout='hideToolTip()'>奚</a><a href='/word_detail.php?id=3632' onmouseover="showToolTip(this, 'zúyǐ', 'sufficient to / so much so that')" onmouseout='hideToolTip()'>足以</a><a href='/word_detail.php?id=5058' onmouseover="showToolTip(this, 'shí', 'to know')" onmouseout='hideToolTip()'>识</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a>。
        <a href='/word_detail.php?id=6373' onmouseover="showToolTip(this, 'jiǎn', 'simple')" onmouseout="hideToolTip()">简</a><a href='/word_detail.php?id=3223' onmouseover="showToolTip(this, 'zǐ', 'child / son')" onmouseout="hideToolTip()">子</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout="hideToolTip()">曰</a><a href='/word_detail.php?id=3670' onmouseover="showToolTip(this, 'shàn', 'virtuous / benevolent / well-disposed')" onmouseout="hideToolTip()">善</a><a href='/word_detail.php?id=6689' onmouseover="showToolTip(this, 'zāi', 'exclamatory or interrogative particle')" onmouseout="hideToolTip()">哉</a><a href='/word_detail.php?id=17405' onmouseover="showToolTip(this, 'Zǐ Gòng', 'Zi Gong')" onmouseout="hideToolTip()">子贡</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout="hideToolTip()">之</a><a href='/word_detail.php?id=3512' onmouseover="showToolTip(this, 'yán', 'to speak / to say')" onmouseout="hideToolTip()">言</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" onmouseout='hideToolTip()'>也</a>。
      </p>
      <p class='example'>
        Zhao Jianzi asked Zi Gong, “How did Confucius conduct himself?”
        Zi Gong said, “I, Ci, cannot know.”
        Vexed, Jian Zi said, “I took you ten years to complete your training in the teachings of Confucius.
        The ruler asks and you reply that you cannot know.  Why?”
        Zi Gong said, “Let me use a metaphor.  It would be like drinking all the rivers and seas to quench one's thirst.
        It is only necessary to be content.
        Confucius is like all the rivers and seas.  As for me, how could I be adequate to understand him?”
        Jian Zi said, “Your words are very virtuous.”
      </p>
      <p>
        This section is from 卷十一 善说 Scroll 11 Kind Words. 
        See [<a href='classical_chinese_references.php#reference'>LIU1</a>].
      </p>
      <h3 class='article'>
        <a name="army"></a>
        <a href='/word_detail.php?id=17404' onmouseover="showToolTip(this, 'Zhào Jiǎnzǐ', 'Zhao Jianzi')" onmouseout='hideToolTip()'>赵简子</a><a href='/word_detail.php?id=808' onmouseover="showToolTip(this, 'jǔ', 'to lift / to hold up')" onmouseout='hideToolTip()'>举</a><a href='/word_detail.php?id=7281' onmouseover="showToolTip(this, 'bīng', 'soldier / troops')" onmouseout='hideToolTip()'>兵</a><a href='/word_detail.php?id=6469' onmouseover="showToolTip(this, 'gōng', 'merit / achievement / result / service / accomplishment / work')" onmouseout='hideToolTip()'>功</a><a href='/word_detail.php?id=17069' onmouseover="showToolTip(this, 'Qí', 'Qi Dynasty')" onmouseout='hideToolTip()'>齐</a>（<a href='/word_detail.php?id=17362' onmouseover="showToolTip(this, 'Shuō Yuàn', 'Garden of Stories')" onmouseout="hideToolTip()">说苑</a>）
        Zhao Jianzi Raises an Army to Attack Qi (Garden of Stories)
      </h3>
      <p class='example'>
        <a href='/word_detail.php?id=17404' onmouseover="showToolTip(this, 'Zhào Jiǎnzǐ', 'Zhao Jianzi')" onmouseout='hideToolTip()'>赵简子</a><a href='/word_detail.php?id=808' onmouseover="showToolTip(this, 'jǔ', 'to lift / to hold up / to raise')" onmouseout='hideToolTip()'>举</a><a href='/word_detail.php?id=7281' onmouseover="showToolTip(this, 'bīng', 'soldier / troops')" onmouseout='hideToolTip()'>兵</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=1404' onmouseover="showToolTip(this, 'gōng', 'to attack / to accuse / to study')" onmouseout='hideToolTip()'>攻</a><a href='/word_detail.php?id=17418' onmouseover="showToolTip(this, 'Qí', 'State of Qi')" onmouseout='hideToolTip()'>齐</a>，<a href='/word_detail.php?id=3958' onmouseover="showToolTip(this, 'lìng', 'to make / to cause to be / to lead / to order')" onmouseout='hideToolTip()'>令</a><a href='/word_detail.php?id=3645' onmouseover="showToolTip(this, 'jūn', 'army / military / arms')" onmouseout='hideToolTip()'>军</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout='hideToolTip()'>中</a><a href='/word_detail.php?id=17195' onmouseover="showToolTip(this, 'gǎn', 'to dare to')" onmouseout='hideToolTip()'>敢</a><a href='/word_detail.php?id=17423' onmouseover="showToolTip(this, 'jiàn', 'to remonstrate / to admonish')" onmouseout='hideToolTip()'>谏</a><a href='/word_detail.php?id=17165' onmouseover="showToolTip(this, 'zhě', 'nominalizing function word')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=3869' onmouseover="showToolTip(this, 'zuì', 'guilt / crime / sin')" onmouseout='hideToolTip()'>罪</a><a href='/word_detail.php?id=17343' onmouseover="showToolTip(this, 'zhì', 'most')" onmouseout='hideToolTip()'>至</a><a href='/word_detail.php?id=3880' onmouseover="showToolTip(this, 'sǐ', 'to die')" 
        onmouseout='hideToolTip()'>死</a>。<a href='/word_detail.php?id=17424' onmouseover="showToolTip(this, 'pī', 'to wear')" onmouseout='hideToolTip()'>被</a><a href='/word_detail.php?id=3648' onmouseover="showToolTip(this, 'jiǎ', 'armour')" onmouseout='hideToolTip()'>甲</a><a href='/word_detail.php?id=17425' onmouseover="showToolTip(this, 'shì', 'an officer / a warrior')" onmouseout='hideToolTip()'>士</a>，<a href='/word_detail.php?id=7131' onmouseover="showToolTip(this, 'míng', 'name')" onmouseout='hideToolTip()'>名</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=3157' onmouseover="showToolTip(this, 'gōng', 'public')" onmouseout='hideToolTip()'>公</a><a href='/word_detail.php?id=6559' onmouseover="showToolTip(this, 'Lú', 'Lu')" onmouseout='hideToolTip()'>卢</a>，<a href='/word_detail.php?id=1270' onmouseover="showToolTip(this, 'wàng', 'to hope / to gaze')" onmouseout='hideToolTip()'>望</a><a href='/word_detail.php?id=2940' onmouseover="showToolTip(this, 'jiàn', 'to see / to meet')" onmouseout='hideToolTip()'>见</a><a href='/word_detail.php?id=6373' onmouseover="showToolTip(this, 'jiǎn', 'simple')" onmouseout='hideToolTip()'>简</a><a href='/word_detail.php?id=3223' onmouseover="showToolTip(this, 'zǐ', 'child / son')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=1114' onmouseover="showToolTip(this, 'dà', 'big / huge / large / major')" onmouseout='hideToolTip()'>大</a><a href='/word_detail.php?id=831' onmouseover="showToolTip(this, 'xiào', 'to smile / to laugh')" 
        onmouseout='hideToolTip()'>笑</a>。<a href='/word_detail.php?id=6373' onmouseover="showToolTip(this, 'jiǎn', 'simple')" onmouseout='hideToolTip()'>简</a><a href='/word_detail.php?id=17151' onmouseover="showToolTip(this, 'zǐ', 'a polite form of address / master')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=17151' onmouseover="showToolTip(this, 'zǐ', 'a polite form of address / master')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=3087' onmouseover="showToolTip(this, 'hé', 'what / how / why / which')" onmouseout='hideToolTip()'>何</a><a href='/word_detail.php?id=831' onmouseover="showToolTip(this, 'xiào', 'to smile / to laugh')" 
        onmouseout='hideToolTip()'>笑</a>。<a href='/word_detail.php?id=723' onmouseover="showToolTip(this, 'duì', 'to')" onmouseout="hideToolTip()">对</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout="hideToolTip()">曰</a>，<a href='/word_detail.php?id=6967' onmouseover="showToolTip(this, 'chén', 'statesman / vassal / courtier / minister / official')" onmouseout="hideToolTip()">臣</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout="hideToolTip()">有</a><a href='/word_detail.php?id=8434' onmouseover="showToolTip(this, 'sù', 'to lodge for the night')" onmouseout="hideToolTip()">宿</a><a href='/word_detail.php?id=831' onmouseover="showToolTip(this, 'xiào', 'to smile / to laugh')" 
        onmouseout="hideToolTip()">笑</a>。<a href='/word_detail.php?id=6373' onmouseover="showToolTip(this, 'jiǎn', 'simple')" onmouseout='hideToolTip()'>简</a><a href='/word_detail.php?id=3223' onmouseover="showToolTip(this, 'zǐ', 'child / son')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=17176' onmouseover="showToolTip(this, 'yǐ', 'to grasp / to use')" onmouseout='hideToolTip()'>以</a><a href='/word_detail.php?id=6660' onmouseover="showToolTip(this, 'jiě', 'to explain / to understand')" onmouseout='hideToolTip()'>解</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=1337' onmouseover="showToolTip(this, 'zé', 'expresses contrast with a previous sentence or clause')" onmouseout='hideToolTip()'>则</a><a href='/word_detail.php?id=948' onmouseover="showToolTip(this, 'kě', 'can / may / able to')" onmouseout='hideToolTip()'>可</a>，<a href='/word_detail.php?id=13465' onmouseover="showToolTip(this, 'wú', 'to not have')" onmouseout='hideToolTip()'>无</a><a href='/word_detail.php?id=17176' onmouseover="showToolTip(this, 'yǐ', 'to grasp / to use')" onmouseout='hideToolTip()'>以</a><a href='/word_detail.php?id=6660' onmouseover="showToolTip(this, 'jiě', 'to explain / to understand')" onmouseout='hideToolTip()'>解</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=1337' onmouseover="showToolTip(this, 'zé', 'expresses contrast with a previous sentence or clause')" onmouseout='hideToolTip()'>则</a><a href='/word_detail.php?id=3880' onmouseover="showToolTip(this, 'sǐ', 'to die')" 
        onmouseout='hideToolTip()'>死</a>。<a href='/word_detail.php?id=1420' onmouseover="showToolTip(this, 'duì', 'to oppose / to face / to regard')" onmouseout='hideToolTip()'>对</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=1166' onmouseover="showToolTip(this, 'dāng', 'to be / to act as')" onmouseout='hideToolTip()'>当</a><a href='/word_detail.php?id=8402' onmouseover="showToolTip(this, 'sāng', 'mulberry tree')" onmouseout='hideToolTip()'>桑</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=524' onmouseover="showToolTip(this, 'shí', 'time / at that time')" onmouseout='hideToolTip()'>时</a>，<a href='/word_detail.php?id=6967' onmouseover="showToolTip(this, 'chén', 'statesman / vassal / courtier / minister / official')" onmouseout='hideToolTip()'>臣</a><a href='/word_detail.php?id=9523' onmouseover="showToolTip(this, 'lín', 'neighbor / adjacent')" onmouseout='hideToolTip()'>邻</a><a href='/word_detail.php?id=745' onmouseover="showToolTip(this, 'jiā', 'family / home')" onmouseout='hideToolTip()'>家</a><a href='/word_detail.php?id=5176' onmouseover="showToolTip(this, 'fū', 'husband / man')" onmouseout='hideToolTip()'>夫</a><a href='/word_detail.php?id=509' onmouseover="showToolTip(this, 'yǔ', 'and')" onmouseout='hideToolTip()'>与</a><a href='/word_detail.php?id=17426' onmouseover="showToolTip(this, 'jū', 'together')" onmouseout='hideToolTip()'>俱</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=815' onmouseover="showToolTip(this, 'tián', 'field')" 
        onmouseout='hideToolTip()'>田</a>。<a href='/word_detail.php?id=2940' onmouseover="showToolTip(this, 'jiàn', 'to see / to meet')" onmouseout='hideToolTip()'>见</a><a href='/word_detail.php?id=8402' onmouseover="showToolTip(this, 'sāng', 'mulberry tree')" onmouseout='hideToolTip()'>桑</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout='hideToolTip()'>中</a><a href='/word_detail.php?id=420' onmouseover="showToolTip(this, 'nǚ', 'female')" onmouseout='hideToolTip()'>女</a>，<a href='/word_detail.php?id=3020' onmouseover="showToolTip(this, 'yīn', 'because')" onmouseout='hideToolTip()'>因</a><a href='/word_detail.php?id=733' onmouseover="showToolTip(this, 'wǎng', 'to go (in a direction)')" onmouseout='hideToolTip()'>往</a><a href='/word_detail.php?id=8199' onmouseover="showToolTip(this, 'zhuī', 'to pursue / to chase')" onmouseout='hideToolTip()'>追</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" onmouseout='hideToolTip()'>之</a>，<a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout='hideToolTip()'>不</a><a href='/word_detail.php?id=1263' onmouseover="showToolTip(this, 'néng', 'can / able')" onmouseout='hideToolTip()'>能</a><a href='/word_detail.php?id=1459' onmouseover="showToolTip(this, 'dé', 'to obtain / to get / to gain')" onmouseout='hideToolTip()'>得</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" 
        onmouseout='hideToolTip()'>之</a>。<a href='/word_detail.php?id=16222' onmouseover="showToolTip(this, 'huán', 'to pay back / to return')" onmouseout='hideToolTip()'>还</a><a href='/word_detail.php?id=17427' onmouseover="showToolTip(this, 'fǎn', 'to go back')" onmouseout='hideToolTip()'>反</a>，<a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=8238' onmouseover="showToolTip(this, 'qī', 'wife')" onmouseout='hideToolTip()'>妻</a><a href='/word_detail.php?id=7307' onmouseover="showToolTip(this, 'nù', 'to be angry / to be in a rage')" onmouseout='hideToolTip()'>怒</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=343' onmouseover="showToolTip(this, 'qù', 'to go')" onmouseout='hideToolTip()'>去</a><a href='/word_detail.php?id=730' onmouseover="showToolTip(this, 'zhī', 'him / her / it')" 
        onmouseout='hideToolTip()'>之</a>。<a href='/word_detail.php?id=6967' onmouseover="showToolTip(this, 'chén', 'statesman / vassal / courtier / minister / official')" onmouseout='hideToolTip()'>臣</a><a href='/word_detail.php?id=831' onmouseover="showToolTip(this, 'xiào', 'to smile / to laugh')" onmouseout='hideToolTip()'>笑</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=17428' onmouseover="showToolTip(this, 'kuàng', 'to be pointless / to be empty')" onmouseout='hideToolTip()'>旷</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" 
        onmouseout='hideToolTip()'>也</a>。<a href='/word_detail.php?id=6373' onmouseover="showToolTip(this, 'jiǎn', 'simple')" onmouseout='hideToolTip()'>简</a><a href='/word_detail.php?id=3223' onmouseover="showToolTip(this, 'zǐ', 'child / son')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=6691' onmouseover="showToolTip(this, 'jīn', 'today / modern / present / current / this / now')" onmouseout='hideToolTip()'>今</a><a href='/word_detail.php?id=17099' onmouseover="showToolTip(this, 'wú', 'I / my')" onmouseout='hideToolTip()'>吾</a><a href='/word_detail.php?id=14566' onmouseover="showToolTip(this, 'fá', 'to cut down / to fell / to attack / to boast')" onmouseout='hideToolTip()'>伐</a><a href='/word_detail.php?id=1075' onmouseover="showToolTip(this, 'guó', 'country')" onmouseout='hideToolTip()'>国</a><a href='/word_detail.php?id=1484' onmouseover="showToolTip(this, 'shī', 'to lose / to miss / to fail')" onmouseout='hideToolTip()'>失</a><a href='/word_detail.php?id=1075' onmouseover="showToolTip(this, 'guó', 'country')" onmouseout='hideToolTip()'>国</a>，<a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout='hideToolTip()'>是</a><a href='/word_detail.php?id=17099' onmouseover="showToolTip(this, 'wú', 'I / my')" onmouseout='hideToolTip()'>吾</a><a href='/word_detail.php?id=17428' onmouseover="showToolTip(this, 'kuàng', 'to be pointless / to be empty')" onmouseout='hideToolTip()'>旷</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" 
        onmouseout='hideToolTip()'>也</a>。<a href='/word_detail.php?id=8983' onmouseover="showToolTip(this, 'yúshì', 'thereupon / as a result / consequently / thus / hence')" onmouseout='hideToolTip()'>于是</a><a href='/word_detail.php?id=11523' onmouseover="showToolTip(this, 'bà', 'to stop / to cease / to dismiss / to suspend / to quit / to finish')" onmouseout='hideToolTip()'>罢</a><a href='/word_detail.php?id=17429' onmouseover="showToolTip(this, 'shī', 'multitude')" onmouseout='hideToolTip()'>师</a><a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=5606' onmouseover="showToolTip(this, 'guī', 'to go back / to return')" 
        onmouseout='hideToolTip()'>归</a>。
      </p>
      <p class='example'>
        Zhao Jianzi raised an army to attack the State of Qi.  He ordered complaining amongst the soldiers to be punished as a crime by execution. 
        An officer wearing armour, named Gong Lu, looked at Jian Zi and laughed wildly.
        Jianzi asked, “Sir, why do you laugh?”
        Facing towards him he said, “You servant spent the whole night laughing.”
        Jian Zi said, “So there is an explanation for it.  There is no other explanation but for you to die.”
        Facing towards him he said, “I was amongst the mulberry trees in the field near the house where my 
        wife and I live.
        Amongst the mulberry trees I saw a woman but, because I was chasing her, I could not catch her.
        Going back, my wife was in a rage and left.”
        Jian Zi said, “Today I attack one state and loose another. It is pointless.
        Therefore, we will stop the campaign and return.”
      </p>
      <p>
        This section of text is from Scroll 9 <a href='/word_detail.php?id=914' onmouseover="showToolTip(this, 'zhèng', 'main / upright / straight')" onmouseout="hideToolTip()">正</a><a href='/word_detail.php?id=17423' onmouseover="showToolTip(this, 'jiàn', 'to remonstrate / to admonish')" onmouseout="hideToolTip()">谏</a>
        Handling Complaints.
      </p>
      <h3 class='article'>
        <a name="kingofwu"></a>
        <a href='/word_detail.php?id=8440' onmouseover="showToolTip(this, 'Wú', 'Wu')" onmouseout='hideToolTip()'>吴</a><a href='/word_detail.php?id=3236' onmouseover="showToolTip(this, 'wáng', 'king / prince')" onmouseout='hideToolTip()'>王</a><a href='/word_detail.php?id=3891' onmouseover="showToolTip(this, 'yù', 'to desire / to wish')" onmouseout='hideToolTip()'>欲</a><a href='/word_detail.php?id=14566' onmouseover="showToolTip(this, 'fá', 'to cut down / to fell / to attack / to boast')" onmouseout='hideToolTip()'>伐</a><a href='/word_detail.php?id=17525' onmouseover="showToolTip(this, 'Jīng', 'the state of Chu')" onmouseout='hideToolTip()'>荆</a>（<a href='/word_detail.php?id=17362' onmouseover="showToolTip(this, 'Shuō Yuàn', 'Garden of Stories')" onmouseout="hideToolTip()">说苑</a>）
        The King of Wu Desired to Attack Chu (Garden of Stories)
      </h3>
      <p class='example'>
        <a href='/word_detail.php?id=8440' onmouseover="showToolTip(this, 'Wú', 'Wu')" onmouseout='hideToolTip()'>吴</a><a href='/word_detail.php?id=3236' onmouseover="showToolTip(this, 'wáng', 'king / prince')" onmouseout='hideToolTip()'>王</a><a href='/word_detail.php?id=3891' onmouseover="showToolTip(this, 'yù', 'to desire / to wish')" onmouseout='hideToolTip()'>欲</a><a href='/word_detail.php?id=14566' onmouseover="showToolTip(this, 'fá', 'to cut down / to fell / to attack / to boast')" onmouseout='hideToolTip()'>伐</a><a href='/word_detail.php?id=17525' onmouseover="showToolTip(this, 'Jīng', 'the state of Chu')" onmouseout='hideToolTip()'>荆</a>，<a href='/word_detail.php?id=3012' onmouseover="showToolTip(this, 'gào', 'to tell / to say')" onmouseout='hideToolTip()'>告</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=17526' onmouseover="showToolTip(this, 'zuǒyòu', 'the left and right / retainers and officials')" onmouseout='hideToolTip()'>左右</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=1659' onmouseover="showToolTip(this, 'gǎn', 'to dare')" onmouseout='hideToolTip()'>敢</a><a href='/word_detail.php?id=17527' onmouseover="showToolTip(this, 'jiàn', 'to remonstrate / to admonish')" onmouseout='hideToolTip()'>諌</a><a href='/word_detail.php?id=17165' onmouseover="showToolTip(this, 'zhě', 'nominalizing function word')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=3880' onmouseover="showToolTip(this, 'sǐ', 'to die')" 
        onmouseout='hideToolTip()'>死</a>。<a href='/word_detail.php?id=17528' onmouseover="showToolTip(this, 'shèrén', 'a palace attendant')" onmouseout='hideToolTip()'>舍人</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=1451' onmouseover="showToolTip(this, 'shào', 'young')" onmouseout='hideToolTip()'>少</a><a href='/word_detail.php?id=17530' onmouseover="showToolTip(this, 'rúzǐ', 'a child')" onmouseout='hideToolTip()'>孺子</a><a href='/word_detail.php?id=17165' onmouseover="showToolTip(this, 'zhě', 'nominalizing function word')" onmouseout='hideToolTip()'>者</a>，<a href='/word_detail.php?id=3891' onmouseover="showToolTip(this, 'yù', 'to desire / to wish')" onmouseout='hideToolTip()'>欲</a><a href='/word_detail.php?id=17423' onmouseover="showToolTip(this, 'jiàn', 'to remonstrate / to admonish')" onmouseout='hideToolTip()'>谏</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout='hideToolTip()'>不</a><a href='/word_detail.php?id=1659' onmouseover="showToolTip(this, 'gǎn', 'to dare')" onmouseout='hideToolTip()'>敢</a>，<a href='/word_detail.php?id=1337' onmouseover="showToolTip(this, 'zé', 'expresses contrast with a previous sentence or clause')" onmouseout='hideToolTip()'>则</a><a href='/word_detail.php?id=8058' onmouseover="showToolTip(this, 'huái', 'mind / heart / bosom')" onmouseout='hideToolTip()'>怀</a><a href='/word_detail.php?id=11392' onmouseover="showToolTip(this, 'wán', 'a pill / a pellet')" onmouseout='hideToolTip()'>丸</a><a href='/word_detail.php?id=2409' onmouseover="showToolTip(this, 'cāo', 'to hold / to drill / to exercise / to act / to do / to take in hand / to keep / to manage')" onmouseout='hideToolTip()'>操</a><a href='/word_detail.php?id=17531' onmouseover="showToolTip(this, 'dàn', 'a slingshot')" onmouseout='hideToolTip()'>弹</a>，<a href='/word_detail.php?id=4349' onmouseover="showToolTip(this, 'yóu', 'to walk / to tour / to roam / to travel')" onmouseout='hideToolTip()'>游</a><a href='/word_detail.php?id=17116' onmouseover="showToolTip(this, 'yú', 'in / at')" onmouseout='hideToolTip()'>于</a><a href='/word_detail.php?id=1149' onmouseover="showToolTip(this, 'hòu', 'after / later / behind')" onmouseout='hideToolTip()'>后</a><a href='/word_detail.php?id=3971' onmouseover="showToolTip(this, 'yuán', 'garden / park')" onmouseout='hideToolTip()'>园</a>，<a href='/word_detail.php?id=6461' onmouseover="showToolTip(this, 'lù', 'dew')" onmouseout='hideToolTip()'>露</a><a href='/word_detail.php?id=13734' onmouseover="showToolTip(this, 'zhān', 'to wet / to moisten')" onmouseout='hideToolTip()'>沾</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=3953' onmouseover="showToolTip(this, 'yī', 'clothes')" 
        onmouseout='hideToolTip()'>衣</a>。<a href='/word_detail.php?id=8840' onmouseover="showToolTip(this, 'rúshì', 'so / thus')" onmouseout='hideToolTip()'>如是</a><a href='/word_detail.php?id=17149' onmouseover="showToolTip(this, 'zhě', 'that / this / it / him / her')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=303' onmouseover="showToolTip(this, 'sān', 'three')" onmouseout='hideToolTip()'>三</a><a href='/word_detail.php?id=6629' onmouseover="showToolTip(this, 'dàn', 'dawn / morning / day-break / day')" 
        onmouseout='hideToolTip()'>旦</a>。<a href='/word_detail.php?id=8440' onmouseover="showToolTip(this, 'Wú', 'Wu')" onmouseout='hideToolTip()'>吴</a><a href='/word_detail.php?id=3236' onmouseover="showToolTip(this, 'wáng', 'king / prince')" onmouseout='hideToolTip()'>王</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=17151' onmouseover="showToolTip(this, 'zǐ', 'a polite form of address / master')" onmouseout='hideToolTip()'>子</a><a href='/word_detail.php?id=370' onmouseover="showToolTip(this, 'lái', 'to come')" 
        onmouseout='hideToolTip()'>来</a>。<a href='/word_detail.php?id=3087' onmouseover="showToolTip(this, 'hé', 'what / how / why / which')" onmouseout='hideToolTip()'>何</a><a href='/word_detail.php?id=17532' onmouseover="showToolTip(this, 'kŭ', 'to grieve bitterly')" onmouseout='hideToolTip()'>苦</a><a href='/word_detail.php?id=13734' onmouseover="showToolTip(this, 'zhān', 'to wet / to moisten')" onmouseout='hideToolTip()'>沾</a><a href='/word_detail.php?id=3953' onmouseover="showToolTip(this, 'yī', 'clothes')" onmouseout='hideToolTip()'>衣</a><a href='/word_detail.php?id=3599' onmouseover="showToolTip(this, 'rúcǐ', 'in this way / so')" 
        onmouseout='hideToolTip()'>如此</a>。<a href='/word_detail.php?id=1420' onmouseover="showToolTip(this, 'duì', 'to oppose / to face / to regard')" onmouseout='hideToolTip()'>对</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a>，<a href='/word_detail.php?id=3971' onmouseover="showToolTip(this, 'yuán', 'garden / park')" onmouseout='hideToolTip()'>园</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout='hideToolTip()'>中</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=2647' onmouseover="showToolTip(this, 'shù', 'tree')" onmouseout='hideToolTip()'>树</a>，<a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=585' onmouseover="showToolTip(this, 'shàng', 'the position on or above something')" onmouseout='hideToolTip()'>上</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=14218' onmouseover="showToolTip(this, 'chán', 'a cicada')" 
        onmouseout='hideToolTip()'>蝉</a>。<a href='/word_detail.php?id=14218' onmouseover="showToolTip(this, 'chán', 'a cicada')" onmouseout='hideToolTip()'>蝉</a><a href='/word_detail.php?id=953' onmouseover="showToolTip(this, 'gāo', 'high / tall')" onmouseout='hideToolTip()'>高</a><a href='/word_detail.php?id=878' onmouseover="showToolTip(this, 'jū', 'to reside')" onmouseout='hideToolTip()'>居</a><a href='/word_detail.php?id=3431' onmouseover="showToolTip(this, 'bēi', 'sadness / sorrow / grief ')" onmouseout='hideToolTip()'>悲</a><a href='/word_detail.php?id=8373' onmouseover="showToolTip(this, 'míng', 'to cry / to chirp (of birds)')" onmouseout='hideToolTip()'>鸣</a><a href='/word_detail.php?id=4358' onmouseover="showToolTip(this, 'yǐn', 'to drink')" onmouseout='hideToolTip()'>饮</a><a href='/word_detail.php?id=6461' onmouseover="showToolTip(this, 'lù', 'dew')" onmouseout='hideToolTip()'>露</a>，<a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout='hideToolTip()'>不</a><a href='/word_detail.php?id=3896' onmouseover="showToolTip(this, 'zhī', 'to know / to be aware')" onmouseout='hideToolTip()'>知</a><a href='/word_detail.php?id=17535' onmouseover="showToolTip(this, 'tángláng', 'a praying mantis')" onmouseout='hideToolTip()'>螳蜋</a><a href='/word_detail.php?id=329' onmouseover="showToolTip(this, 'zài', 'at')" onmouseout='hideToolTip()'>在</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=1149' onmouseover="showToolTip(this, 'hòu', 'after / later / behind')" onmouseout='hideToolTip()'>后</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" 
        onmouseout='hideToolTip()'>也</a>。<a href='/word_detail.php?id=17535' onmouseover="showToolTip(this, 'tángláng', 'a praying mantis')" onmouseout='hideToolTip()'>螳蜋</a><a href='/word_detail.php?id=17536' onmouseover="showToolTip(this, 'wěi shēn', 'to bend the body')" onmouseout='hideToolTip()'>委身</a><a href='/word_detail.php?id=17537' onmouseover="showToolTip(this, 'qǔ', 'to bend')" onmouseout='hideToolTip()'>曲</a><a href='/word_detail.php?id=1943' onmouseover="showToolTip(this, 'fù', 'to add / to attach / to be close to / to be attached')" onmouseout='hideToolTip()'>附</a><a href='/word_detail.php?id=3891' onmouseover="showToolTip(this, 'yù', 'to desire / to wish')" onmouseout='hideToolTip()'>欲</a><a href='/word_detail.php?id=3026' onmouseover="showToolTip(this, 'qǔ', 'to take / to get / to choose / to fetch')" onmouseout='hideToolTip()'>取</a><a href='/word_detail.php?id=14218' onmouseover="showToolTip(this, 'chán', 'a cicada')" onmouseout='hideToolTip()'>蝉</a>，<a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=4874' onmouseover="showToolTip(this, 'bùgù', 'in spite of / regardless of')" onmouseout='hideToolTip()'>不顾</a><a href='/word_detail.php?id=3896' onmouseover="showToolTip(this, 'zhī', 'to know / to be aware')" onmouseout='hideToolTip()'>知</a><a href='/word_detail.php?id=17538' onmouseover="showToolTip(this, 'huángquè', 'titmouse / a small bird')" onmouseout="hideToolTip()">黄雀</a><a href='/word_detail.php?id=329' onmouseover="showToolTip(this, 'zài', 'at')" onmouseout='hideToolTip()'>在</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=9353' onmouseover="showToolTip(this, 'páng', 'side')" onmouseout='hideToolTip()'>旁</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" 
        onmouseout='hideToolTip()'>也</a>。<a href='/word_detail.php?id=17538' onmouseover="showToolTip(this, 'huángquè', 'titmouse / a small bird')" onmouseout='hideToolTip()'>黄雀</a><a href='/word_detail.php?id=7670' onmouseover="showToolTip(this, 'yán', 'to prolong / to extend / to delay')" onmouseout='hideToolTip()'>延</a><a href='/word_detail.php?id=15224' onmouseover="showToolTip(this, 'jǐng', 'the neck')" onmouseout='hideToolTip()'>颈</a><a href='/word_detail.php?id=3891' onmouseover="showToolTip(this, 'yù', 'to desire / to wish')" onmouseout='hideToolTip()'>欲</a><a href='/word_detail.php?id=16867' onmouseover="showToolTip(this, 'zhuó', 'to peck')" onmouseout='hideToolTip()'>啄</a><a href='/word_detail.php?id=17535' onmouseover="showToolTip(this, 'tángláng', 'a praying mantis')" onmouseout='hideToolTip()'>螳蜋</a>，<a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout='hideToolTip()'>不</a><a href='/word_detail.php?id=3896' onmouseover="showToolTip(this, 'zhī', 'to know / to be aware')" onmouseout='hideToolTip()'>知</a><a href='/word_detail.php?id=17531' onmouseover="showToolTip(this, 'dàn', 'a slingshot')" onmouseout='hideToolTip()'>弹</a><a href='/word_detail.php?id=11392' onmouseover="showToolTip(this, 'wán', 'a pill / a pellet')" onmouseout='hideToolTip()'>丸</a><a href='/word_detail.php?id=329' onmouseover="showToolTip(this, 'zài', 'at')" onmouseout='hideToolTip()'>在</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=581' onmouseover="showToolTip(this, 'xià', 'bottom')" onmouseout='hideToolTip()'>下</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" 
        onmouseout='hideToolTip()'>也</a>。<a href='/word_detail.php?id=624' onmouseover="showToolTip(this, 'cǐ', 'this, these')" onmouseout='hideToolTip()'>此</a><a href='/word_detail.php?id=303' onmouseover="showToolTip(this, 'sān', 'three')" onmouseout='hideToolTip()'>三</a><a href='/word_detail.php?id=17149' onmouseover="showToolTip(this, 'zhě', 'that / this / it / him / her')" onmouseout='hideToolTip()'>者</a><a href='/word_detail.php?id=5046' onmouseover="showToolTip(this, 'jiē', 'all / each and every / in all cases')" onmouseout='hideToolTip()'>皆</a><a href='/word_detail.php?id=17539' onmouseover="showToolTip(this, 'wù', 'to labor at')" onmouseout='hideToolTip()'>务</a><a href='/word_detail.php?id=3891' onmouseover="showToolTip(this, 'yù', 'to desire / to wish')" onmouseout='hideToolTip()'>欲</a><a href='/word_detail.php?id=1459' onmouseover="showToolTip(this, 'dé', 'to obtain / to get / to gain')" onmouseout='hideToolTip()'>得</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=681' onmouseover="showToolTip(this, 'qián', 'in front of / before')" onmouseout='hideToolTip()'>前</a><a href='/word_detail.php?id=3673' onmouseover="showToolTip(this, 'lì', 'advantage / benefit')" onmouseout='hideToolTip()'>利</a>，<a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout='hideToolTip()'>而</a><a href='/word_detail.php?id=4874' onmouseover="showToolTip(this, 'bùgù', 'in spite of / regardless of')" onmouseout='hideToolTip()'>不顾</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=1149' onmouseover="showToolTip(this, 'hòu', 'after / later / behind')" onmouseout='hideToolTip()'>后</a><a href='/word_detail.php?id=13788' onmouseover="showToolTip(this, 'zhī', 'used between a modifier and a word to form a word group')" onmouseout='hideToolTip()'>之</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout='hideToolTip()'>有</a><a href='/word_detail.php?id=17540' onmouseover="showToolTip(this, 'huàn', 'a misfortune')" onmouseout='hideToolTip()'>患</a><a href='/word_detail.php?id=8853' onmouseover="showToolTip(this, 'yě', 'a final modal particle indicating certainy or decision')" 
        onmouseout='hideToolTip()'>也</a>。<a href='/word_detail.php?id=8440' onmouseover="showToolTip(this, 'Wú', 'Wu')" onmouseout='hideToolTip()'>吴</a><a href='/word_detail.php?id=3236' onmouseover="showToolTip(this, 'wáng', 'king / prince')" onmouseout='hideToolTip()'>王</a><a href='/word_detail.php?id=5110' onmouseover="showToolTip(this, 'yuē', 'to speak / to say')" onmouseout='hideToolTip()'>曰</a><a href='/word_detail.php?id=3670' onmouseover="showToolTip(this, 'shàn', 'virtuous / benevolent / well-disposed')" onmouseout='hideToolTip()'>善</a><a href='/word_detail.php?id=6689' onmouseover="showToolTip(this, 'zāi', 'exclamatory or interrogative particle')" onmouseout='hideToolTip()'>哉</a><a href='/word_detail.php?id=5071' onmouseover="showToolTip(this, 'nǎi', 'thus / so / therefore / then / only / thereupon')" onmouseout='hideToolTip()'>乃</a><a href='/word_detail.php?id=11523' onmouseover="showToolTip(this, 'bà', 'to stop / to cease / to dismiss / to suspend / to quit / to finish')" onmouseout='hideToolTip()'>罢</a><a href='/word_detail.php?id=1574' onmouseover="showToolTip(this, 'qí', 'his / her / its / theirs / that')" onmouseout='hideToolTip()'>其</a><a href='/word_detail.php?id=7281' onmouseover="showToolTip(this, 'bīng', 'soldier / troops')" 
        onmouseout='hideToolTip()'>兵</a>。
      </p>
      <p class='example'>
        The King of Wu desired to attack Chu and told his retainers and officials that anyone 
        complaining would be executed.
        A palace attendant with a small child wanted to object but did not dare. Rather he held a 
        slingshot with a pellet in on his body and walked to the back garden where his clothes got 
        wet with due.
        So he spent three dawns.
        The King of Wu said, “Sir, please come here.
        What greivance wet your clothes in this way?”
        He said, “In there garden there are some trees with cicadas on them.
        The cicadas live up high and sadly weep, drinking due.  There is a praying mantis 
        back here as well.
        The praying mantis bends its body hoping to catch a cicada in spite of the small bird at 
        its side.
        The small bird stretches its neck wanting to catch the praying mantis not knowing that 
        there is a slingshot pellet below it.
        These three times I have been laboring to take the advantage but each time has ended in 
        failure.”
        The King of Wu said, “Excellent!” He thus dismissed his troups.
      </p>
      <p>
        
      </p>
      <div class="prevNext">
        <a href="classical_chinese_embedded.php">Previous</a> &nbsp;
        <a href="classical_chinese.php">Contents</a> &nbsp;
        <a href="classical_chinese_zhanguoce.php">Next</a>
      </div>
    </div>
<?php
  	require_once 'footer2.txt';
?>
    <div>
      <span id="toolTip"><span id="pinyinSpan">Pinyin</span> <span id="englishSpan">English</span></span>
    </div>
  </body>
</html>
