<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="content-type"/>
    <title>Chinese Notes - Grammar 中文笔记 - 语法</title>
    <link rel="shortcut icon" href="/favicon.ico"/>
    <link rel="stylesheet" type="text/css" href="styles.css"/>
    <meta name="keywords"
          content="A web site for learning (Mandarin) Chinese. Grammar 语法 Chinese English bilingual 双言"/>
    <meta name="description"
          content="Chinese Notes &mdash; Grammar 汉语笔记 - 语法"/>
    <script type="text/javascript" src="script/chinesenotes.js"></script>
  </head>
  <body>
    <span id="toolTip"><span id="pinyinSpan">Pinyin</span> <span id="englishSpan">English</span></span>
    <div class="breadcrumbs">
      <a href="index.html">Chinese Notes 中文笔记</a> &gt; 
      <a href="reference.php">Reference 参考</a> &gt; 
      <a href="grammar.php">Grammar 语法</a> &gt;
      Complex Sentences 复句
    </div>      
    <h1 class='article'>汉语语法入门 An Introduction to Chinese Grammar</h1>
    <div class="box">
      <div class='fright'>
        <form action='/word_detail.php' method='post'>
          <div>
	      <input type='text' name='word' size='50'/>
          <input id='searchButton' type='submit' value='搜索 Search' title='搜索 Sōusuǒ Search'/>
          </div>
        </form>
      </div>
      <h2 class='article'>
        <a href='/word_detail.php?id=9267' onmouseover="showToolTip(this, '複句 fùjù', 'a complex sentence')" 
        onmouseout="hideToolTip()">复句</a>
        Complex Sentences
      </h2>
      <p>
        <a href='/word_detail.php?id=9267' onmouseover="showToolTip(this, '複句 fùjù', 'a complex sentence')" onmouseout="hideToolTip()">复句</a><a href='/word_detail.php?id=951' onmouseover="showToolTip(this, 'yóu', 'follow / from / it is for...to / reason / cause')" onmouseout="hideToolTip()">由</a><a href='/word_detail.php?id=312' onmouseover="showToolTip(this, '兩 liǎng', 'two')" onmouseout="hideToolTip()">两</a><a href='/word_detail.php?id=281' onmouseover="showToolTip(this, '個 gè', 'individual / unit')" onmouseout="hideToolTip()">个</a><a href='/word_detail.php?id=2027' onmouseover="showToolTip(this, 'huò', 'or')" onmouseout="hideToolTip()">或</a><a href='/word_detail.php?id=312' onmouseover="showToolTip(this, '兩 liǎng', 'two')" onmouseout="hideToolTip()">两</a><a href='/word_detail.php?id=281' onmouseover="showToolTip(this, '個 gè', 'individual / unit')" onmouseout="hideToolTip()">个</a><a href='/word_detail.php?id=365' onmouseover="showToolTip(this, 'yǐshàng', 'more than / above / over / the above-mentioned')" onmouseout="hideToolTip()">以上</a><a href='/word_detail.php?id=9266' onmouseover="showToolTip(this, '單句 dānjù', 'simple sentence')" onmouseout="hideToolTip()">单句</a><a href='/word_detail.php?id=1993' onmouseover="showToolTip(this, '構成 gòuchéng', 'to constitute / to form / to compose')" onmouseout="hideToolTip()">构成</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a>，<a href='/word_detail.php?id=383' onmouseover="showToolTip(this, 'suǒ', 'measure word for houses, small buildings and institutions')" onmouseout="hideToolTip()">所</a><a href='/word_detail.php?id=4266' onmouseover="showToolTip(this, 'bāohán', 'to contain / to embody / to include')" onmouseout="hideToolTip()">包含</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9266' onmouseover="showToolTip(this, '單句 dānjù', 'simple sentence')" onmouseout="hideToolTip()">单句</a><a href='/word_detail.php?id=5688' onmouseover="showToolTip(this, 'jiào', 'to call / to yell / to be called / to order')" onmouseout="hideToolTip()">叫</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" 
        onmouseout="hideToolTip()">分句</a>。<a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=387' onmouseover="showToolTip(this, 'hé', 'and')" onmouseout="hideToolTip()">和</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=389' onmouseover="showToolTip(this, '之間 zhījiān', 'between / among')" onmouseout="hideToolTip()">之间</a><a href='/word_detail.php?id=721' onmouseover="showToolTip(this, 'yòng', 'to use')" onmouseout="hideToolTip()">用</a><a href='/word_detail.php?id=2771' onmouseover="showToolTip(this, '逗號 dòuhào', 'comma')" onmouseout="hideToolTip()">逗号</a>“，”<a href='/word_detail.php?id=2027' onmouseover="showToolTip(this, 'huò', 'or')" onmouseout="hideToolTip()">或</a><a href='/word_detail.php?id=2772' onmouseover="showToolTip(this, '分號 fēnhào', 'semicolon')" onmouseout="hideToolTip()">分号</a>“；”<a href='/word_detail.php?id=1915' onmouseover="showToolTip(this, 'dàibiǎo', 'representative / delegate')" onmouseout="hideToolTip()">代表</a><a href='/word_detail.php?id=11172' onmouseover="showToolTip(this, '語音 yǔyīn', 'voice')" onmouseout="hideToolTip()">语音</a><a href='/word_detail.php?id=16171' onmouseover="showToolTip(this, '停頓 tíngdùn', 'to pause')" 
        onmouseout="hideToolTip()">停顿</a>。<a href='/word_detail.php?id=2846' onmouseover="showToolTip(this, 'bǐrú', 'for example / for instance / such as')" 
        onmouseout="hideToolTip()">比如</a>：
      </p>
      <p>
        Complex sentences are made up of two or more simple sentences.
        The simple sentences that complex sentences are composed from are called clauses.
        In between the clauses a comma or a semicolon is used to represent a pause in spoken language.
        For example,
      </p>
      <ol>
        <li>
          <a href='/word_detail.php?id=4081' onmouseover="showToolTip(this, 'nǐ', 'you')" onmouseout="hideToolTip()">你</a><a href='/word_detail.php?id=973' onmouseover="showToolTip(this, '點 diǎn', 'point / dot /downwards-right convex character stroke')" onmouseout="hideToolTip()">点</a><a href='/word_detail.php?id=301' onmouseover="showToolTip(this, 'yī', 'one')" onmouseout="hideToolTip()">一</a><a href='/word_detail.php?id=281' onmouseover="showToolTip(this, '個 gè', 'individual / unit')" onmouseout="hideToolTip()">个</a><a href='/word_detail.php?id=20877' onmouseover="showToolTip(this, '葷 hūn​', 'meat')" onmouseout="hideToolTip()">荤</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a>，<a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=973' onmouseover="showToolTip(this, '點 diǎn', 'point / dot /downwards-right convex character stroke')" onmouseout="hideToolTip()">点</a><a href='/word_detail.php?id=301' onmouseover="showToolTip(this, 'yī', 'one')" onmouseout="hideToolTip()">一</a><a href='/word_detail.php?id=281' onmouseover="showToolTip(this, '個 gè', 'individual / unit')" onmouseout="hideToolTip()">个</a><a href='/word_detail.php?id=3237' onmouseover="showToolTip(this, 'sù', 'plain / white')" onmouseout="hideToolTip()">素</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" 
          onmouseout="hideToolTip()">的</a>。
          (You order a meat dish, I will order a vegetarian dish.)
          <p>
            <a href='/word_detail.php?id=312' onmouseover="showToolTip(this, '兩 liǎng', 'two')" onmouseout="hideToolTip()">两</a><a href='/word_detail.php?id=281' onmouseover="showToolTip(this, '個 gè', 'individual / unit')" onmouseout="hideToolTip()">个</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout="hideToolTip()">有</a><a href='/word_detail.php?id=12883' onmouseover="showToolTip(this, '邏輯 luóji', 'logic')" onmouseout="hideToolTip()">逻辑</a><a href='/word_detail.php?id=584' onmouseover="showToolTip(this, 'shàng', 'above / previous')" onmouseout="hideToolTip()">上</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" 
            onmouseout="hideToolTip()">关系</a>。
            (The two clauses have a logical connection.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=518' onmouseover="showToolTip(this, 'tā', 'he him')" onmouseout="hideToolTip()">他</a><a href='/word_detail.php?id=7250' onmouseover="showToolTip(this, '籃球 lánqiú', 'basketball')" onmouseout="hideToolTip()">篮球</a><a href='/word_detail.php?id=4954' onmouseover="showToolTip(this, 'dǎ', 'to beat / to strike / to hit / to type / to mix up / to fetch / to shoot / to calculate')" onmouseout="hideToolTip()">打</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" onmouseout="hideToolTip()">好</a>，（<a href='/word_detail.php?id=518' onmouseover="showToolTip(this, 'tā', 'he him')" onmouseout="hideToolTip()">他</a>）<a href='/word_detail.php?id=4136' onmouseover="showToolTip(this, 'zúqiú', 'football / soccer')" onmouseout="hideToolTip()">足球</a><a href='/word_detail.php?id=925' onmouseover="showToolTip(this, 'yě', 'also')" onmouseout="hideToolTip()">也</a><a href='/word_detail.php?id=9852' onmouseover="showToolTip(this, 'tī', 'kick / play')" onmouseout="hideToolTip()">踢</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=285' onmouseover="showToolTip(this, 'hǎo', 'good / very')" 
          onmouseout="hideToolTip()">好</a>。
          (He plays basketball well and [he] also plays soccer well.) 
          <p>
            <a href='/word_detail.php?id=2769' onmouseover="showToolTip(this, 'jùzi', 'sentence')" onmouseout="hideToolTip()">句子</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout="hideToolTip()">有</a><a href='/word_detail.php?id=12883' onmouseover="showToolTip(this, '邏輯 luóji', 'logic')" onmouseout="hideToolTip()">逻辑</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" 
            onmouseout="hideToolTip()">关系</a>。
            (If the clauses have the same subject then it is only necessary to write it once.)
          </p>
        </li>
        <li>
          <span class='hl'>因为</span><a href='/word_detail.php?id=264' onmouseover="showToolTip(this, '現在 xiànzài', 'at present / in the process of')" onmouseout="hideToolTip()">现在</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=12134' onmouseover="showToolTip(this, 'gāofēng', 'peak / summit / height')" onmouseout="hideToolTip()">高峰</a>，<span class='hl'>所以</span><a href='/word_detail.php?id=9372' onmouseover="showToolTip(this, 'lùshang', 'on the road / on a journey / road surface')" onmouseout="hideToolTip()">路上</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=3966' onmouseover="showToolTip(this, '車 chē', 'vehicle')" onmouseout="hideToolTip()">车</a><a href='/word_detail.php?id=654' onmouseover="showToolTip(this, 'hěn', 'very')" onmouseout="hideToolTip()">很</a><a href='/word_detail.php?id=400' onmouseover="showToolTip(this, 'duō', 'indicates a number greater than the number preceding it')" 
          onmouseout="hideToolTip()">多</a>。
          (Since it is peak hour, so there are a lot of cars on the road.)
          <p>
            <a href='/word_detail.php?id=8169' onmouseover="showToolTip(this, '這個 zhège', 'this / this one')" onmouseout="hideToolTip()">这个</a><a href='/word_detail.php?id=9267' onmouseover="showToolTip(this, '複句 fùjù', 'a complex sentence')" onmouseout="hideToolTip()">复句</a><a href='/word_detail.php?id=721' onmouseover="showToolTip(this, 'yòng', 'to use')" onmouseout="hideToolTip()">用</a><a href='/word_detail.php?id=20878' onmouseover="showToolTip(this, '關聯詞 guānlián cí', 'a correlative')" onmouseout="hideToolTip()">关联词</a>“<a href='/word_detail.php?id=1369' onmouseover="showToolTip(this, '因為 yīnwèi', 'because / owing to / on account of')" onmouseout="hideToolTip()">因为</a>…<a href='/word_detail.php?id=4851' onmouseover="showToolTip(this, 'suǒyǐ', 'therefore / as a result / so')" onmouseout="hideToolTip()">所以</a>”<a href='/word_detail.php?id=334' onmouseover="showToolTip(this, 'biǎoshì', 'to express')" onmouseout="hideToolTip()">表示</a><a href='/word_detail.php?id=282' onmouseover="showToolTip(this, 'gè', 'each / every')" onmouseout="hideToolTip()">各</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=389' onmouseover="showToolTip(this, '之間 zhījiān', 'between / among')" onmouseout="hideToolTip()">之间</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" 
            onmouseout="hideToolTip()">关系</a>。
            (This complex sentence uses the correlatives <a href='/word_detail.php?id=1369' onmouseover="showToolTip(this, '因為 yīnwèi', 'because / owing to / on account of')" onmouseout="hideToolTip()">因为</a>…<a href='/word_detail.php?id=4851' onmouseover="showToolTip(this, 'suǒyǐ', 'therefore / as a result / so')" 
            onmouseout="hideToolTip()">所以</a> to express the relationship between the clauses.)
          </p>
        </li>
      </ol>
      <p>
        <a href='/word_detail.php?id=20878' onmouseover="showToolTip(this, '關聯詞 guānlián cí', 'a correlative')" onmouseout="hideToolTip()">关联词</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" 
        onmouseout="hideToolTip()">是</a>：
      </p>
      <p>
        Correlatives are
      </p>
      <ol>
        <li>
          <a href='/word_detail.php?id=2461' onmouseover="showToolTip(this, '連接 liánjiē', 'to link / to join / to attach')" onmouseout="hideToolTip()">连接</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9274' onmouseover="showToolTip(this, '連詞 liáncí', 'conjunction')" 
          onmouseout="hideToolTip()">连词</a>
          (Conjunctions that connect clauses)
          <p>
            <span class='hl'>不但</span><a href='/word_detail.php?id=7458' onmouseover="showToolTip(this, 'zhuàng', 'to hit / to strike')" onmouseout="hideToolTip()">撞</a><a href='/word_detail.php?id=3966' onmouseover="showToolTip(this, '車 chē', 'vehicle')" onmouseout="hideToolTip()">车</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=399' onmouseover="showToolTip(this, 'rén', 'person / people')" onmouseout="hideToolTip()">人</a><a href='/word_detail.php?id=20871' onmouseover="showToolTip(this, '酒後駕車 jiǔ​ hòu​ jià ​chē', 'to drink and drive / driving under the influence (DUI)')" onmouseout="hideToolTip()">酒后驾车</a>，<span class='hl'>而且</span><a href='/word_detail.php?id=518' onmouseover="showToolTip(this, 'tā', 'he him')" onmouseout="hideToolTip()">他</a><a href='/word_detail.php?id=20865' onmouseover="showToolTip(this, 'táo​yì​', 'to escape / to run away / to abscond')" onmouseout="hideToolTip()">逃逸</a><a href='/word_detail.php?id=16356' onmouseover="showToolTip(this, '現場 xiànchǎng', 'scene')" 
            onmouseout="hideToolTip()">现场</a>。
            (Not only was the driver of the car that collided driving under the influence but he also fled the scene.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=1746' onmouseover="showToolTip(this, 'jùyǒu', 'to have / to possess')" onmouseout="hideToolTip()">具有</a><a href='/word_detail.php?id=6091' onmouseover="showToolTip(this, '關聯 guānlián', 'related / linked / affiliated')" onmouseout="hideToolTip()">关联</a><a href='/word_detail.php?id=618' onmouseover="showToolTip(this, 'zuòyòng', 'to play a role')" onmouseout="hideToolTip()">作用</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9271' onmouseover="showToolTip(this, '副詞 fùcí', 'adverb')" 
          onmouseout="hideToolTip()">副词</a>
          (Adverbs with a connecting function)
          <p>
            <a href='/word_detail.php?id=518' onmouseover="showToolTip(this, 'tā', 'he him')" onmouseout="hideToolTip()">他</a><span class='hl'>又</span><a href='/word_detail.php?id=567' onmouseover="showToolTip(this, '會 huì', 'can / be possible / be able to / to assemble / to meet')" onmouseout="hideToolTip()">会</a><a href='/word_detail.php?id=1274' onmouseover="showToolTip(this, '數學 shùxué', 'math')" onmouseout="hideToolTip()">数学</a>，<span class='hl'>又</span><a href='/word_detail.php?id=567' onmouseover="showToolTip(this, '會 huì', 'can / be possible / be able to / to assemble / to meet')" onmouseout="hideToolTip()">会</a><a href='/word_detail.php?id=3838' onmouseover="showToolTip(this, '彈 tán', 'to pluck a string / to play')" onmouseout="hideToolTip()">弹</a><a href='/word_detail.php?id=4190' onmouseover="showToolTip(this, '鋼琴 gāngqín', 'piano')" 
            onmouseout="hideToolTip()">钢琴</a>。
            (He can do math and he can also play the piano.)
          </p>
        </li>
      </ol>
      <p>
        <a href='/word_detail.php?id=9267' onmouseover="showToolTip(this, '複句 fùjù', 'a complex sentence')" onmouseout="hideToolTip()">复句</a><a href='/word_detail.php?id=599' onmouseover="showToolTip(this, 'kěyǐ', 'can / may / possible / able to')" onmouseout="hideToolTip()">可以</a><a href='/word_detail.php?id=9264' onmouseover="showToolTip(this, 'fēnchéng', 'to divide / to break into parts')" onmouseout="hideToolTip()">分成</a><a href='/word_detail.php?id=20880' onmouseover="showToolTip(this, '並列 bìngliè fùjù', 'a coordinate complex sentence')" onmouseout="hideToolTip()">并列复句</a><a href='/word_detail.php?id=387' onmouseover="showToolTip(this, 'hé', 'and')" onmouseout="hideToolTip()">和</a><a href='/word_detail.php?id=20881' onmouseover="showToolTip(this, '偏正複句 piānzhèng fùjù', 'a subordindate complex sentence')" onmouseout="hideToolTip()">偏正复句</a><a href='/word_detail.php?id=312' onmouseover="showToolTip(this, '兩 liǎng', 'two')" onmouseout="hideToolTip()">两</a><a href='/word_detail.php?id=4536' onmouseover="showToolTip(this, '類 lèi', 'kind / type / class / category')" 
        onmouseout="hideToolTip()">类</a>。
      </p>
      <p>
        Complex sentences can be divided into the two types coordinate complex sentence and subordindate complex sentences.
      </p>
      <p>
        <a href='/word_detail.php?id=20932' onmouseover="showToolTip(this, '緊縮句 jǐnsuō jù', 'a contracted sentence')" onmouseout="hideToolTip()">紧缩句</a><a href='/word_detail.php?id=721' onmouseover="showToolTip(this, 'yòng', 'to use')" onmouseout="hideToolTip()">用</a><a href='/word_detail.php?id=20461' onmouseover="showToolTip(this, '簡句 jiǎn jù', 'a simple sentence')" onmouseout="hideToolTip()">简句</a><a href='/word_detail.php?id=20926' onmouseover="showToolTip(this, 'jù​shì​', 'sentence pattern / sentence structure / syntax')" onmouseout="hideToolTip()">句式</a><a href='/word_detail.php?id=334' onmouseover="showToolTip(this, 'biǎoshì', 'to express')" onmouseout="hideToolTip()">表示</a><a href='/word_detail.php?id=9267' onmouseover="showToolTip(this, '複句 fùjù', 'a complex sentence')" onmouseout="hideToolTip()">复句</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=276' onmouseover="showToolTip(this, 'nèiróng', 'content')" 
        onmouseout="hideToolTip()">内容</a>。<a href='/word_detail.php?id=6052' onmouseover="showToolTip(this, 'lìrú', 'for example / for instance / such as')" 
        onmouseout="hideToolTip()">例如</a>：
      </p>
      <p>
        Contracted sentences express the content of a complex sentence with the syntax of a simple sentence.
        For example,
      </p>
      <ol>
        <li>
          <a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=3414' onmouseover="showToolTip(this, '頭 tóu', 'head')" onmouseout="hideToolTip()">头</a><a href='/word_detail.php?id=4747' onmouseover="showToolTip(this, 'téng', 'pain / ache')" onmouseout="hideToolTip()">疼</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=343' onmouseover="showToolTip(this, 'qù', 'to go')" 
          onmouseout="hideToolTip()">去</a>。
          (I have a headache, I am not going.)
          <p>
            <a href='/word_detail.php?id=5246' onmouseover="showToolTip(this, 'yìsi', 'idea / opinion / meaning')" onmouseout="hideToolTip()">意思</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a>：<a href='/word_detail.php?id=1369' onmouseover="showToolTip(this, '因為 yīnwèi', 'because / owing to / on account of')" onmouseout="hideToolTip()">因为</a>“<a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=20933' onmouseover="showToolTip(this, '頭疼 tóu​téng​', 'a headache')" onmouseout="hideToolTip()">头疼</a>”，<a href='/word_detail.php?id=4851' onmouseover="showToolTip(this, 'suǒyǐ', 'therefore / as a result / so')" onmouseout="hideToolTip()">所以</a><a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a>“<a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=343' onmouseover="showToolTip(this, 'qù', 'to go')" 
            onmouseout="hideToolTip()">去</a>”。
            (This means that because <a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=20933' onmouseover="showToolTip(this, '頭疼 tóu​téng​', 'a headache')" 
            onmouseout="hideToolTip()">头疼</a> so <a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=343' onmouseover="showToolTip(this, 'qù', 'to go')" 
            onmouseout="hideToolTip()">去</a>.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=707' onmouseover="showToolTip(this, 'xiǎng', 'to think / to want')" onmouseout="hideToolTip()">想</a><a href='/word_detail.php?id=412' onmouseover="showToolTip(this, '說 shuō', 'to say / said / to speak')" onmouseout="hideToolTip()">说</a><a href='/word_detail.php?id=902' onmouseover="showToolTip(this, 'jiù', 'right away / only / precisely')" onmouseout="hideToolTip()">就</a><a href='/word_detail.php?id=412' onmouseover="showToolTip(this, '說 shuō', 'to say / said / to speak')" 
          onmouseout="hideToolTip()">说</a>。
          (If I feel like saying something then I will.)
          <p>
            <a href='/word_detail.php?id=9274' onmouseover="showToolTip(this, '連詞 liáncí', 'conjunction')" onmouseout="hideToolTip()">连词</a>“<a href='/word_detail.php?id=2661' onmouseover="showToolTip(this, 'rúguǒ', 'if / in case / in the event that')" onmouseout="hideToolTip()">如果</a>”<a href='/word_detail.php?id=16010' onmouseover="showToolTip(this, 'shěnglüè', 'to omit')" onmouseout="hideToolTip()">省略</a><a href='/word_detail.php?id=393' onmouseover="showToolTip(this, 'le', 'completion of an action')" 
            onmouseout="hideToolTip()">了</a>。
            (The conjunction <a href='/word_detail.php?id=2661' onmouseover="showToolTip(this, 'rúguǒ', 'if / in case / in the event that')" 
            onmouseout='hideToolTip()'>如果</a> is omitted.)
          </p>
        </li>
      </ol>
      <h3 class='article'>
        <a name='coordinate'></a>
        <a href='/word_detail.php?id=20880' onmouseover="showToolTip(this, '並列 bìngliè fùjù', 'a coordinate complex sentence')" 
        onmouseout="hideToolTip()">并列复句</a>
        Coordinate Complex Sentences
      </h3>
      <p>
        <a href='/word_detail.php?id=20880' onmouseover="showToolTip(this, '並列 bìngliè fùjù', 'a coordinate complex sentence')" onmouseout="hideToolTip()">并列复句</a><a href='/word_detail.php?id=951' onmouseover="showToolTip(this, 'yóu', 'follow / from / it is for...to / reason / cause')" onmouseout="hideToolTip()">由</a><a href='/word_detail.php?id=334' onmouseover="showToolTip(this, 'biǎoshì', 'to express')" onmouseout="hideToolTip()">表示</a><a href='/word_detail.php?id=9195' onmouseover="showToolTip(this, '並列 bìngliè', 'to stand side by side / to be juxtaposed')" onmouseout="hideToolTip()">并列</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=1993' onmouseover="showToolTip(this, '構成 gòuchéng', 'to constitute / to form / to compose')" onmouseout="hideToolTip()">构成</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" 
        onmouseout="hideToolTip()">的</a>。<a href='/word_detail.php?id=20880' onmouseover="showToolTip(this, '並列 bìngliè fùjù', 'a coordinate complex sentence')" onmouseout="hideToolTip()">并列复句</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout="hideToolTip()">中</a><a href='/word_detail.php?id=282' onmouseover="showToolTip(this, 'gè', 'each / every')" onmouseout="hideToolTip()">各</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=757' onmouseover="showToolTip(this, 'dōu', 'all')" onmouseout="hideToolTip()">都</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=7182' onmouseover="showToolTip(this, 'píngděng', 'equal')" onmouseout="hideToolTip()">平等</a>，<a href='/word_detail.php?id=751' onmouseover="showToolTip(this, 'méiyǒu', 'to not have / there is not')" onmouseout="hideToolTip()">没有</a><a href='/word_detail.php?id=20907' onmouseover="showToolTip(this, 'zhǔcì', 'primary and secondary')" onmouseout="hideToolTip()">主次</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" 
        onmouseout="hideToolTip()">关系</a>。<a href='/word_detail.php?id=2846' onmouseover="showToolTip(this, 'bǐrú', 'for example / for instance / such as')" 
        onmouseout="hideToolTip()">比如</a>：
      </p>
      <p>
        A coordinate complex sentence is composed of clauses with coordinate relations.
        In a coordinate complex sentence all the clauses are equal, there are no primary-secondary relations. 
        For example,
      </p>
      <ol>
        <li>
          <a href='/word_detail.php?id=8537' onmouseover="showToolTip(this, 'bù shì', 'no / is not / not')" onmouseout="hideToolTip()">不是</a><a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=707' onmouseover="showToolTip(this, 'xiǎng', 'to think / to want')" onmouseout="hideToolTip()">想</a><a href='/word_detail.php?id=1158' onmouseover="showToolTip(this, '幫助 bāngzhù', 'help / assistance / aid')" onmouseout="hideToolTip()">帮助</a>，<a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout="hideToolTip()">而</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=567' onmouseover="showToolTip(this, '會 huì', 'can / be possible / be able to / to assemble / to meet')" 
          onmouseout="hideToolTip()">会</a>。
          (It is not that I don't want to help, it is that I don't know how.)
          <p>
            <a href='/word_detail.php?id=1374' onmouseover="showToolTip(this, '聯合 liánhé', 'to combine / to join / to unite')" onmouseout="hideToolTip()">联合</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a>，<a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=1000' onmouseover="showToolTip(this, '分別 fēnbié', 'to differentiate / to distinguish')" onmouseout="hideToolTip()">分别</a><a href='/word_detail.php?id=1514' onmouseover="showToolTip(this, '說明 shuōmíng', 'to explain')" onmouseout="hideToolTip()">说明</a><a href='/word_detail.php?id=312' onmouseover="showToolTip(this, '兩 liǎng', 'two')" onmouseout="hideToolTip()">两</a><a href='/word_detail.php?id=2274' onmouseover="showToolTip(this, 'jiàn', 'a document')" onmouseout="hideToolTip()">件</a><a href='/word_detail.php?id=9642' onmouseover="showToolTip(this, 'shìqíng', 'affair / matter / thing')" 
            onmouseout="hideToolTip()">事情</a>。
            (This is a coordinative relation where the clauses each explain two different matters.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=4031' onmouseover="showToolTip(this, 'háizǐ', 'child')" onmouseout="hideToolTip()">孩子</a><a href='/word_detail.php?id=10408' onmouseover="showToolTip(this, '下課 xiàkè', 'to finish class')" onmouseout="hideToolTip()">下课</a><a href='/word_detail.php?id=670' onmouseover="showToolTip(this, '以後 yǐhòu', 'afterwards')" onmouseout="hideToolTip()">以后</a>，<a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=603' onmouseover="showToolTip(this, 'dào', 'arrive / receive')" onmouseout="hideToolTip()">到</a><a href='/word_detail.php?id=1233' onmouseover="showToolTip(this, '學校 xuéxiào', 'school')" onmouseout="hideToolTip()">学校</a><a href='/word_detail.php?id=2924' onmouseover="showToolTip(this, 'jiē', 'to extend / to connect / to receive / to catch / to join')" onmouseout="hideToolTip()">接</a><a href='/word_detail.php?id=518' onmouseover="showToolTip(this, 'tā', 'he him')" 
          onmouseout="hideToolTip()">他</a>。
          (When the child finishes class, I will go to school to pick him up.)
          <p>
            <a href='/word_detail.php?id=18015' onmouseover="showToolTip(this, 'chéngjiē', 'to follow / to continue')" onmouseout="hideToolTip()">承接</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a>，<a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=2924' onmouseover="showToolTip(this, 'jiē', 'to extend / to connect / to receive / to catch / to join')" onmouseout="hideToolTip()">接</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=2791' onmouseover="showToolTip(this, '先後 xiānhòu', 'in succession / early or late')" onmouseout="hideToolTip()">先后</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout="hideToolTip()">有</a><a href='/word_detail.php?id=8270' onmouseover="showToolTip(this, '順序 shùnxù', 'sequence / order')" 
            onmouseout="hideToolTip()">顺序</a>。
            (Successive relation, there is a sequence in the arrangement of the clauses.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=8169' onmouseover="showToolTip(this, '這個 zhège', 'this / this one')" onmouseout="hideToolTip()">这个</a><a href='/word_detail.php?id=580' onmouseover="showToolTip(this, 'xià', 'next')" onmouseout="hideToolTip()">下</a><a href='/word_detail.php?id=10150' onmouseover="showToolTip(this, 'hóuzi', 'monkey')" onmouseout="hideToolTip()">猴子</a><a href='/word_detail.php?id=693' onmouseover="showToolTip(this, 'bùdàn', 'not only')" onmouseout="hideToolTip()">不但</a><a href='/word_detail.php?id=9478' onmouseover="showToolTip(this, '聰明 cōngming', 'clever / intelligent / bright / smart / acute')" onmouseout="hideToolTip()">聪明</a>，<a href='/word_detail.php?id=552' onmouseover="showToolTip(this, 'érqiě', 'not only ... but also .... / ... as well as ... / moreover / in addition / furthermore')" onmouseout="hideToolTip()">而且</a><a href='/word_detail.php?id=10902' onmouseover="showToolTip(this, '能幹 nénggàn', 'capable / competent')" 
          onmouseout="hideToolTip()">能干</a>。
          (This young man is not only clever but is very capable.)
          <p>
            <a href='/word_detail.php?id=20882' onmouseover="showToolTip(this, '遞進 dì​jìn​', 'to progress gradually')" onmouseout="hideToolTip()">递进</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a>，<a href='/word_detail.php?id=9338' onmouseover="showToolTip(this, '後面 hòumian', 'rear / back / behind / later / afterwards')" onmouseout="hideToolTip()">后面</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=1303' onmouseover="showToolTip(this, 'bì', 'to associate with / be near')" onmouseout="hideToolTip()">比</a><a href='/word_detail.php?id=613' onmouseover="showToolTip(this, 'qiánmiàn', 'in front of / facing')" onmouseout="hideToolTip()">前面</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=965' onmouseover="showToolTip(this, 'gèng', 'more / even more')" onmouseout="hideToolTip()">更</a><a href='/word_detail.php?id=570' onmouseover="showToolTip(this, '進一步 jìnyībù', 'one step further')" 
            onmouseout="hideToolTip()">进一步</a>。
            (Progressive relation, the second clause progresses a step beyond the first clause.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=4081' onmouseover="showToolTip(this, 'nǐ', 'you')" onmouseout="hideToolTip()">你</a><a href='/word_detail.php?id=707' onmouseover="showToolTip(this, 'xiǎng', 'to think / to want')" onmouseout="hideToolTip()">想</a><a href='/word_detail.php?id=4792' onmouseover="showToolTip(this, 'chī', 'to eat')" onmouseout="hideToolTip()">吃</a><a href='/word_detail.php?id=10112' onmouseover="showToolTip(this, '米飯 mǐfàn', 'cooked rice')" onmouseout="hideToolTip()">米饭</a>，<a href='/word_detail.php?id=1141' onmouseover="showToolTip(this, '還是 háishì', 'still / nevertheless')" onmouseout="hideToolTip()">还是</a><a href='/word_detail.php?id=707' onmouseover="showToolTip(this, 'xiǎng', 'to think / to want')" onmouseout="hideToolTip()">想</a><a href='/word_detail.php?id=4792' onmouseover="showToolTip(this, 'chī', 'to eat')" onmouseout="hideToolTip()">吃</a><a href='/word_detail.php?id=3411' onmouseover="showToolTip(this, 'miàn', 'side / surface / aspect / face')" 
          onmouseout="hideToolTip()">面</a>？
          (Would you like to eat rice or eat noodles?)
          <p>
            <a href='/word_detail.php?id=627' onmouseover="showToolTip(this, '選擇 xuǎnzé', 'to select / to choose')" onmouseout="hideToolTip()">选择</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a>，<a href='/word_detail.php?id=312' onmouseover="showToolTip(this, '兩 liǎng', 'two')" onmouseout="hideToolTip()">两</a><a href='/word_detail.php?id=281' onmouseover="showToolTip(this, '個 gè', 'individual / unit')" onmouseout="hideToolTip()">个</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9642' onmouseover="showToolTip(this, 'shìqíng', 'affair / matter / thing')" onmouseout="hideToolTip()">事情</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=1263' onmouseover="showToolTip(this, 'néng', 'can / able')" onmouseout="hideToolTip()">能</a><a href='/word_detail.php?id=958' onmouseover="showToolTip(this, '同時 tóngshí', 'at the same time / simultaneously')" onmouseout="hideToolTip()">同时</a><a href='/word_detail.php?id=14055' onmouseover="showToolTip(this, '併存 bìngcún', 'to coexist')" 
            onmouseout="hideToolTip()">并存</a>。
            (Alternative relation, the two conditions cannot coexist.)
          </p>
        </li>
      </ol>
      <p>
        <a href='/word_detail.php?id=20880' onmouseover="showToolTip(this, '並列 bìngliè fùjù', 'a coordinate complex sentence')" onmouseout="hideToolTip()">并列复句</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout="hideToolTip()">中</a><a href='/word_detail.php?id=335' onmouseover="showToolTip(this, 'yào', 'to want ')" onmouseout="hideToolTip()">要</a><a href='/word_detail.php?id=9249' onmouseover="showToolTip(this, '主語 zhǔyǔ', 'subject')" onmouseout="hideToolTip()">主语</a><a href='/word_detail.php?id=20878' onmouseover="showToolTip(this, '關聯詞 guānlián cí', 'a correlative')" onmouseout="hideToolTip()">关联词</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=2758' onmouseover="showToolTip(this, 'wèizhi', 'position / place / seat')" 
        onmouseout="hideToolTip()">位置</a>：
      </p>
      <p>
        Attention needs to be given to the position of correlatives in coordinate complex sentences:
      </p>
      <ol>
        <li>
          <span class='hl'>不管</span><a href='/word_detail.php?id=366' onmouseover="showToolTip(this, '我們 wǒmen', 'we')" onmouseout="hideToolTip()">我们</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=5774' onmouseover="showToolTip(this, 'péngyou', 'friend')" onmouseout="hideToolTip()">朋友</a>，<span class='hl'>但是</span><a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=397' onmouseover="showToolTip(this, '還 hái', 'also / in addition / more')" onmouseout="hideToolTip()">还</a><a href='/word_detail.php?id=411' onmouseover="showToolTip(this, 'de', 'a sentence particle used after a verb to show effect / degree or possibility')" onmouseout="hideToolTip()">得</a><a href='/word_detail.php?id=775' onmouseover="showToolTip(this, '給 gěi', 'for the benefit of / to give')" onmouseout="hideToolTip()">给</a><a href='/word_detail.php?id=4081' onmouseover="showToolTip(this, 'nǐ', 'you')" onmouseout="hideToolTip()">你</a><a href='/word_detail.php?id=3088' onmouseover="showToolTip(this, 'tíxǐng', 'to remind / to call attention to / to warn of')" onmouseout="hideToolTip()">提醒</a><a href='/word_detail.php?id=271' onmouseover="showToolTip(this, '這 zhè', 'this / these')" onmouseout="hideToolTip()">这</a><a href='/word_detail.php?id=2274' onmouseover="showToolTip(this, 'jiàn', 'a document')" onmouseout="hideToolTip()">件</a><a href='/word_detail.php?id=1219' onmouseover="showToolTip(this, 'shì', 'matter / thing / item')" 
          onmouseout="hideToolTip()">事</a>。
          (Even though we are friends, I have to remind you about this matter.)
          <p>
            <a href='/word_detail.php?id=2661' onmouseover="showToolTip(this, 'rúguǒ', 'if / in case / in the event that')" onmouseout="hideToolTip()">如果</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9249' onmouseover="showToolTip(this, '主語 zhǔyǔ', 'subject')" onmouseout="hideToolTip()">主语</a><a href='/word_detail.php?id=2193' onmouseover="showToolTip(this, 'bùtóng', 'different / distinct / not the same')" onmouseout="hideToolTip()">不同</a>，<a href='/word_detail.php?id=9274' onmouseover="showToolTip(this, '連詞 liáncí', 'conjunction')" onmouseout="hideToolTip()">连词</a><a href='/word_detail.php?id=335' onmouseover="showToolTip(this, 'yào', 'to want ')" onmouseout="hideToolTip()">要</a><a href='/word_detail.php?id=1290' onmouseover="showToolTip(this, 'fàng', 'to put / to place')" onmouseout="hideToolTip()">放</a><a href='/word_detail.php?id=9249' onmouseover="showToolTip(this, '主語 zhǔyǔ', 'subject')" onmouseout="hideToolTip()">主语</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9343' onmouseover="showToolTip(this, '前邊 qiánbian', 'front')" 
            onmouseout="hideToolTip()">前边</a>。
            (If the subjects of the clauses are different then conjunctions should be placed before the subjects.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=8745' onmouseover="showToolTip(this, '咱們 zánmen', 'we (inclusive)')" onmouseout="hideToolTip()">咱们</a><a href='/word_detail.php?id=10342' onmouseover="showToolTip(this, '倆 liǎ', 'two')" onmouseout="hideToolTip()">俩</a><span class='hl'>不但</span><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=12119' onmouseover="showToolTip(this, 'tóngshì', 'colleague / co-worker')" onmouseout="hideToolTip()">同事</a>，<span class='hl'>而且</span><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=5774' onmouseover="showToolTip(this, 'péngyou', 'friend')" 
          onmouseout="hideToolTip()">朋友</a>。
          (Not only are the two of us coworkers but we are also friends.)
          <p>
            <a href='/word_detail.php?id=2661' onmouseover="showToolTip(this, 'rúguǒ', 'if / in case / in the event that')" onmouseout="hideToolTip()">如果</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9249' onmouseover="showToolTip(this, '主語 zhǔyǔ', 'subject')" onmouseout="hideToolTip()">主语</a><a href='/word_detail.php?id=2197' onmouseover="showToolTip(this, 'xiāngtóng', 'identical / same')" onmouseout="hideToolTip()">相同</a>，<a href='/word_detail.php?id=1290' onmouseover="showToolTip(this, 'fàng', 'to put / to place')" onmouseout="hideToolTip()">放</a><a href='/word_detail.php?id=9274' onmouseover="showToolTip(this, '連詞 liáncí', 'conjunction')" onmouseout="hideToolTip()">连词</a><a href='/word_detail.php?id=328' onmouseover="showToolTip(this, 'zài', 'in / at')" onmouseout="hideToolTip()">在</a><a href='/word_detail.php?id=9249' onmouseover="showToolTip(this, '主語 zhǔyǔ', 'subject')" onmouseout="hideToolTip()">主语</a><a href='/word_detail.php?id=9344' onmouseover="showToolTip(this, '後邊 hòubiān', 'back')" 
            onmouseout="hideToolTip()">后边</a>。
            (If the clauses have the same subject then the conjunctions should be placed after the subject.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=8745' onmouseover="showToolTip(this, '咱們 zánmen', 'we (inclusive)')" onmouseout="hideToolTip()">咱们</a><a href='/word_detail.php?id=2165' onmouseover="showToolTip(this, 'xiān', 'first / in advance')" onmouseout="hideToolTip()">先</a><a href='/word_detail.php?id=4792' onmouseover="showToolTip(this, 'chī', 'to eat')" onmouseout="hideToolTip()">吃</a><a href='/word_detail.php?id=4352' onmouseover="showToolTip(this, '飯 fàn', 'food / cuisine / cooked rice / meal')" onmouseout="hideToolTip()">饭</a>，<a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=670' onmouseover="showToolTip(this, '以後 yǐhòu', 'afterwards')" onmouseout="hideToolTip()">以后</a><span class='hl'>才</span><a href='/word_detail.php?id=534' onmouseover="showToolTip(this, 'chūqù', 'to go out')" onmouseout="hideToolTip()">出去</a><a href='/word_detail.php?id=825' onmouseover="showToolTip(this, '買 mǎi', 'to buy')" onmouseout="hideToolTip()">买</a><a href='/word_detail.php?id=7390' onmouseover="showToolTip(this, '東西 dōngxi', 'thing')" 
          onmouseout="hideToolTip()">东西</a>。
          <p>
            <a href='/word_detail.php?id=9271' onmouseover="showToolTip(this, '副詞 fùcí', 'adverb')" onmouseout="hideToolTip()">副词</a><a href='/word_detail.php?id=10450' onmouseover="showToolTip(this, '總是 zǒngshì', 'always')" onmouseout="hideToolTip()">总是</a><a href='/word_detail.php?id=335' onmouseover="showToolTip(this, 'yào', 'to want ')" onmouseout="hideToolTip()">要</a><a href='/word_detail.php?id=1290' onmouseover="showToolTip(this, 'fàng', 'to put / to place')" onmouseout="hideToolTip()">放</a><a href='/word_detail.php?id=328' onmouseover="showToolTip(this, 'zài', 'in / at')" onmouseout="hideToolTip()">在</a><a href='/word_detail.php?id=9249' onmouseover="showToolTip(this, '主語 zhǔyǔ', 'subject')" onmouseout="hideToolTip()">主语</a><a href='/word_detail.php?id=9344' onmouseover="showToolTip(this, '後邊 hòubiān', 'back')" 
            onmouseout="hideToolTip()">后边</a>。
            (Adverbs are always placed after the subject.)
          </p>
        </li>
      </ol>
      <p>
        <a href='/word_detail.php?id=20880' onmouseover="showToolTip(this, '並列 bìngliè fùjù', 'a coordinate complex sentence')" onmouseout="hideToolTip()">并列复句</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout="hideToolTip()">中</a><a href='/word_detail.php?id=9803' onmouseover="showToolTip(this, '常見 chángjiàn', 'common')" onmouseout="hideToolTip()">常见</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=20878' onmouseover="showToolTip(this, '關聯詞 guānlián cí', 'a correlative')" onmouseout="hideToolTip()">关联词</a><a href='/word_detail.php?id=687' onmouseover="showToolTip(this, 'bāokuò', 'to include')" 
        onmouseout="hideToolTip()">包括</a>：<a href='/word_detail.php?id=8537' onmouseover="showToolTip(this, 'bù shì', 'no / is not / not')" onmouseout="hideToolTip()">不是</a>、<a href='/word_detail.php?id=9385' onmouseover="showToolTip(this, '還是 háishì', 'or')" onmouseout='hideToolTip()'>还是</a>，<a href='/word_detail.php?id=397' onmouseover="showToolTip(this, '還 hái', 'also / in addition / more')" onmouseout="hideToolTip()">还</a>、<a href='/word_detail.php?id=2169' onmouseover="showToolTip(this, '然後 ránhòu', 'after / after that / afterwards')" onmouseout="hideToolTip()">然后</a>、<a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout="hideToolTip()">而</a>、<a href='/word_detail.php?id=552' onmouseover="showToolTip(this, 'érqiě', 'not only ... but also .... / ... as well as ... / moreover / in addition / furthermore')" onmouseout="hideToolTip()">而且</a>、<a href='/word_detail.php?id=2027' onmouseover="showToolTip(this, 'huò', 'or')" onmouseout="hideToolTip()">或</a>、<a href='/word_detail.php?id=1973' onmouseover="showToolTip(this, 'huòzhě', 'or')" onmouseout="hideToolTip()">或者</a>、<a href='/word_detail.php?id=902' onmouseover="showToolTip(this, 'jiù', 'right away / only / precisely')" onmouseout="hideToolTip()">就</a>、<a href='/word_detail.php?id=6767' onmouseover="showToolTip(this, 'yòu', 'expresses the existence of simultaneous conditions')" onmouseout='hideToolTip()'>又</a>、<a href='/word_detail.php?id=925' onmouseover="showToolTip(this, 'yě', 'also')" onmouseout="hideToolTip()">也</a>、<a href='/word_detail.php?id=693' onmouseover="showToolTip(this, 'bùdàn', 'not only')" onmouseout="hideToolTip()">不但</a>、<a href='/word_detail.php?id=11134' onmouseover="showToolTip(this, '一邊 yībiān', 'on the one hand / on the other hand / doing while')" onmouseout='hideToolTip()'>一边</a>、<a href='/word_detail.php?id=20912' onmouseover="showToolTip(this, 'yī​miàn', 'simultaneously')" onmouseout='hideToolTip()'>一面</a>、<a href='/word_detail.php?id=20916' onmouseover="showToolTip(this, 'yī​fāng​miàn', 'on the one hand / on the other hand')" 
        onmouseout='hideToolTip()'>一方面</a>。
      </p>
      <p>
        Commonly encountered correlatives in coordinate complex sentences include <a href='/word_detail.php?id=8537' onmouseover="showToolTip(this, 'bù shì', 'no / is not / not')" onmouseout="hideToolTip()">不是</a>、<a href='/word_detail.php?id=9385' onmouseover="showToolTip(this, '還是 háishì', 'or')" onmouseout='hideToolTip()'>还是</a>，<a href='/word_detail.php?id=397' onmouseover="showToolTip(this, '還 hái', 'also / in addition / more')" onmouseout="hideToolTip()">还</a>、<a href='/word_detail.php?id=2169' onmouseover="showToolTip(this, '然後 ránhòu', 'after / after that / afterwards')" onmouseout="hideToolTip()">然后</a>、<a href='/word_detail.php?id=1336' onmouseover="showToolTip(this, 'ér', 'and / as well as / but (not) / yet (not)')" onmouseout="hideToolTip()">而</a>、<a href='/word_detail.php?id=552' onmouseover="showToolTip(this, 'érqiě', 'not only ... but also .... / ... as well as ... / moreover / in addition / furthermore')" onmouseout="hideToolTip()">而且</a>、<a href='/word_detail.php?id=2027' onmouseover="showToolTip(this, 'huò', 'or')" onmouseout="hideToolTip()">或</a>、<a href='/word_detail.php?id=1973' onmouseover="showToolTip(this, 'huòzhě', 'or')" onmouseout="hideToolTip()">或者</a>、<a href='/word_detail.php?id=902' onmouseover="showToolTip(this, 'jiù', 'right away / only / precisely')" onmouseout="hideToolTip()">就</a>、<a href='/word_detail.php?id=6767' onmouseover="showToolTip(this, 'yòu', 'expresses the existence of simultaneous conditions')" onmouseout='hideToolTip()'>又</a>、<a href='/word_detail.php?id=925' onmouseover="showToolTip(this, 'yě', 'also')" onmouseout="hideToolTip()">也</a>、<a href='/word_detail.php?id=693' onmouseover="showToolTip(this, 'bùdàn', 'not only')" onmouseout="hideToolTip()">不但</a>、<a href='/word_detail.php?id=11134' onmouseover="showToolTip(this, '一邊 yībiān', 'on the one hand / on the other hand / doing while')" onmouseout='hideToolTip()'>一边</a>、<a href='/word_detail.php?id=20912' onmouseover="showToolTip(this, 'yī​miàn', 'simultaneously')" onmouseout='hideToolTip()'>一面</a>、and <a href='/word_detail.php?id=20916' onmouseover="showToolTip(this, 'yī​fāng​miàn', 'on the one hand / on the other hand')" 
        onmouseout='hideToolTip()'>一方面</a>.
      </p>
      <h3 class='article'>
        <a name='subordinate'></a>
        <a href='/word_detail.php?id=20881' onmouseover="showToolTip(this, '偏正複句 piānzhèng fùjù', 'a subordindate complex sentence')" 
        onmouseout="hideToolTip()">偏正复句</a>
        Subordinate Complex Sentences
      </h3>
      <p>
        <a href='/word_detail.php?id=20881' onmouseover="showToolTip(this, '偏正複句 piānzhèng fùjù', 'a subordindate complex sentence')" onmouseout="hideToolTip()">偏正复句</a><a href='/word_detail.php?id=951' onmouseover="showToolTip(this, 'yóu', 'follow / from / it is for...to / reason / cause')" onmouseout="hideToolTip()">由</a><a href='/word_detail.php?id=1746' onmouseover="showToolTip(this, 'jùyǒu', 'to have / to possess')" onmouseout="hideToolTip()">具有</a><a href='/word_detail.php?id=2878' onmouseover="showToolTip(this, 'piān', 'to be one-sided / to lean / to slant / to be prejudiced / to be inclined')" onmouseout="hideToolTip()">偏</a><a href='/word_detail.php?id=914' onmouseover="showToolTip(this, 'zhèng', 'main / upright / straight')" onmouseout="hideToolTip()">正</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=1993' onmouseover="showToolTip(this, '構成 gòuchéng', 'to constitute / to form / to compose')" onmouseout="hideToolTip()">构成</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a>，<a href='/word_detail.php?id=282' onmouseover="showToolTip(this, 'gè', 'each / every')" onmouseout="hideToolTip()">各</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=389' onmouseover="showToolTip(this, '之間 zhījiān', 'between / among')" onmouseout="hideToolTip()">之间</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout="hideToolTip()">有</a><a href='/word_detail.php?id=2681' onmouseover="showToolTip(this, 'zhǔ', 'owner / host')" onmouseout="hideToolTip()">主</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" onmouseout="hideToolTip()">有</a><a href='/word_detail.php?id=667' onmouseover="showToolTip(this, 'cì', 'time')" 
        onmouseout="hideToolTip()">次</a>。<a href='/word_detail.php?id=6052' onmouseover="showToolTip(this, 'lìrú', 'for example / for instance / such as')" 
        onmouseout="hideToolTip()">例如</a>：
      </p>
      <p>
        A subordindate complex sentence is composed of clauses with a subordinate relation.  
        Between the clauses there is a primary and a secondary.
        For example,
      </p>
      <ol>
        <li>
          <a href='/word_detail.php?id=592' onmouseover="showToolTip(this, '儘管 jǐnguǎn', 'despite / although / even though')" onmouseout="hideToolTip()">尽管</a><a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=7550' onmouseover="showToolTip(this, 'zǎochén', 'early morning')" onmouseout="hideToolTip()">早晨</a><a href='/word_detail.php?id=306' onmouseover="showToolTip(this, 'liù', 'six')" onmouseout="hideToolTip()">六</a><a href='/word_detail.php?id=973' onmouseover="showToolTip(this, '點 diǎn', 'point / dot /downwards-right convex character stroke')" onmouseout="hideToolTip()">点</a><a href='/word_detail.php?id=603' onmouseover="showToolTip(this, 'dào', 'arrive / receive')" onmouseout="hideToolTip()">到</a><a href='/word_detail.php?id=393' onmouseover="showToolTip(this, 'le', 'completion of an action')" onmouseout="hideToolTip()">了</a><a href='/word_detail.php?id=20923' onmouseover="showToolTip(this, '售票處 shòu​piào ​chù', 'ticket office')" onmouseout="hideToolTip()">售票处</a>，<a href='/word_detail.php?id=697' onmouseover="showToolTip(this, 'dànshì', 'but')" onmouseout="hideToolTip()">但是</a><a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=397' onmouseover="showToolTip(this, '還 hái', 'also / in addition / more')" onmouseout="hideToolTip()">还</a><a href='/word_detail.php?id=1255' onmouseover="showToolTip(this, '沒 méi', '(negative prefix for verbs) / have not / not')" onmouseout="hideToolTip()">没</a><a href='/word_detail.php?id=825' onmouseover="showToolTip(this, '買 mǎi', 'to buy')" onmouseout="hideToolTip()">买</a><a href='/word_detail.php?id=603' onmouseover="showToolTip(this, 'dào', 'arrive / receive')" onmouseout="hideToolTip()">到</a><a href='/word_detail.php?id=4183' onmouseover="showToolTip(this, 'piào', 'ticket / vote')" 
          onmouseout="hideToolTip()">票</a>。
          (Even though I arrived at the ticket office at 6 am, I was still not able to buy a ticket.)
          <p>
            <a href='/word_detail.php?id=16850' onmouseover="showToolTip(this, '轉折 zhuǎnzhé', 'turning point')" onmouseout="hideToolTip()">转折</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a>，<a href='/word_detail.php?id=9343' onmouseover="showToolTip(this, '前邊 qiánbian', 'front')" onmouseout="hideToolTip()">前边</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=20921' onmouseover="showToolTip(this, 'piānjù', 'subordinate clause')" onmouseout="hideToolTip()">偏句</a>，<a href='/word_detail.php?id=9344' onmouseover="showToolTip(this, '後邊 hòubiān', 'back')" onmouseout="hideToolTip()">后边</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=277' onmouseover="showToolTip(this, 'shì', 'is / are / am / yes / to be')" onmouseout="hideToolTip()">是</a><a href='/word_detail.php?id=20922' onmouseover="showToolTip(this, 'zhèngjù', 'main clause')" 
            onmouseout="hideToolTip()">正句</a>。
            (Contrasting relation &mdash; the first clause is the subordinate clause and and the second clause is the main clause.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=1369' onmouseover="showToolTip(this, '因為 yīnwèi', 'because / owing to / on account of')" onmouseout="hideToolTip()">因为</a><a href='/word_detail.php?id=321' onmouseover="showToolTip(this, 'wǒ', 'I / me')" onmouseout="hideToolTip()">我</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=819' onmouseover="showToolTip(this, '電視機 diànshìjī', 'television (set)')" onmouseout="hideToolTip()">电视机</a><a href='/word_detail.php?id=4500' onmouseover="showToolTip(this, '壞 huài', 'bad / spoiled / broken')" onmouseout="hideToolTip()">坏</a><a href='/word_detail.php?id=393' onmouseover="showToolTip(this, 'le', 'completion of an action')" onmouseout="hideToolTip()">了</a>，<a href='/word_detail.php?id=4851' onmouseover="showToolTip(this, 'suǒyǐ', 'therefore / as a result / so')" onmouseout="hideToolTip()">所以</a><a href='/word_detail.php?id=1255' onmouseover="showToolTip(this, '沒 méi', '(negative prefix for verbs) / have not / not')" onmouseout="hideToolTip()">没</a><a href='/word_detail.php?id=8892' onmouseover="showToolTip(this, '辦法 bànfǎ', 'means / method')" onmouseout="hideToolTip()">办法</a><a href='/word_detail.php?id=537' onmouseover="showToolTip(this, 'kàn', 'to see / to look')" onmouseout="hideToolTip()">看</a><a href='/word_detail.php?id=20597' onmouseover="showToolTip(this, '冬奧會 Dōng​'ào Huì', 'Winter Olympics')" 
          onmouseout="hideToolTip()">冬奥会</a>。
          (Because my television was broken, there was no way for me to watch the Winter Olympics.)
          <p>
            <a href='/word_detail.php?id=16952' onmouseover="showToolTip(this, 'yīn guǒ', 'cause and effect / karma')" onmouseout="hideToolTip()">因果</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a>，<a href='/word_detail.php?id=9343' onmouseover="showToolTip(this, '前邊 qiánbian', 'front')" onmouseout="hideToolTip()">前边</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a>（<a href='/word_detail.php?id=20921' onmouseover="showToolTip(this, 'piānjù', 'subordinate clause')" onmouseout="hideToolTip()">偏句</a>）<a href='/word_detail.php?id=1514' onmouseover="showToolTip(this, '說明 shuōmíng', 'to explain')" onmouseout="hideToolTip()">说明</a><a href='/word_detail.php?id=5400' onmouseover="showToolTip(this, 'yuányīn', 'cause / origin / root cause / reason')" onmouseout="hideToolTip()">原因</a>，<a href='/word_detail.php?id=9344' onmouseover="showToolTip(this, '後邊 hòubiān', 'back')" onmouseout="hideToolTip()">后边</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a>（<a href='/word_detail.php?id=20922' onmouseover="showToolTip(this, 'zhèngjù', 'main clause')" onmouseout="hideToolTip()">正句</a>）<a href='/word_detail.php?id=1514' onmouseover="showToolTip(this, '說明 shuōmíng', 'to explain')" onmouseout="hideToolTip()">说明</a><a href='/word_detail.php?id=2307' onmouseover="showToolTip(this, '結果 jiéguǒ', 'outcome / result / conclusion')" 
            onmouseout="hideToolTip()">结果</a>。
            (Causative relation &mdash; the first clause [the subordinate clause] explains the reason and the second clause
            [the main clause] explains the result.)
          </p>
        </li>
        <li>
          <a href='/word_detail.php?id=2661' onmouseover="showToolTip(this, 'rúguǒ', 'if / in case / in the event that')" onmouseout="hideToolTip()">如果</a><a href='/word_detail.php?id=502' onmouseover="showToolTip(this, 'bù', 'not / no')" onmouseout="hideToolTip()">不</a><a href='/word_detail.php?id=9460' onmouseover="showToolTip(this, 'xiǎoxīn', 'to be careful')" onmouseout="hideToolTip()">小心</a>，<a href='/word_detail.php?id=8872' onmouseover="showToolTip(this, 'yìwài', 'accident / mishap')" onmouseout="hideToolTip()">意外</a><a href='/word_detail.php?id=567' onmouseover="showToolTip(this, '會 huì', 'can / be possible / be able to / to assemble / to meet')" onmouseout="hideToolTip()">会</a><a href='/word_detail.php?id=500' onmouseover="showToolTip(this, '發生 fāshēng', 'to happen / to occur / to take place')" onmouseout="hideToolTip()">发生</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" 
          onmouseout="hideToolTip()">的</a>。
          (If you are not careful, an accident may happen.)
          <p>
            <a href='/word_detail.php?id=8992' onmouseover="showToolTip(this, '假設 jiǎshè', 'hypothesis / conjecture')" onmouseout="hideToolTip()">假设</a><a href='/word_detail.php?id=2027' onmouseover="showToolTip(this, 'huò', 'or')" onmouseout="hideToolTip()">或</a><a href='/word_detail.php?id=1714' onmouseover="showToolTip(this, '條件 tiáojiàn', 'condition / prerequisite')" onmouseout="hideToolTip()">条件</a><a href='/word_detail.php?id=262' onmouseover="showToolTip(this, '關係 guānxì', 'relations')" onmouseout="hideToolTip()">关系</a>，<a href='/word_detail.php?id=9343' onmouseover="showToolTip(this, '前邊 qiánbian', 'front')" onmouseout="hideToolTip()">前边</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=1514' onmouseover="showToolTip(this, '說明 shuōmíng', 'to explain')" onmouseout="hideToolTip()">说明</a><a href='/word_detail.php?id=1714' onmouseover="showToolTip(this, '條件 tiáojiàn', 'condition / prerequisite')" onmouseout="hideToolTip()">条件</a>，<a href='/word_detail.php?id=9344' onmouseover="showToolTip(this, '後邊 hòubiān', 'back')" onmouseout="hideToolTip()">后边</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=9268' onmouseover="showToolTip(this, 'fēnjù', 'clause')" onmouseout="hideToolTip()">分句</a><a href='/word_detail.php?id=1514' onmouseover="showToolTip(this, '說明 shuōmíng', 'to explain')" onmouseout="hideToolTip()">说明</a><a href='/word_detail.php?id=1714' onmouseover="showToolTip(this, '條件 tiáojiàn', 'condition / prerequisite')" onmouseout="hideToolTip()">条件</a><a href='/word_detail.php?id=2272' onmouseover="showToolTip(this, 'yīxià', 'one time / once / for a short time')" onmouseout="hideToolTip()">一下</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=2307' onmouseover="showToolTip(this, '結果 jiéguǒ', 'outcome / result / conclusion')" 
            onmouseout="hideToolTip()">结果</a>。
            (Supposition or conditional relation &mdash; the first clause explains the condition and the second clause explains the result
            if the condition is satisfied.)
          </p>
        </li>
      </ol>
      <p>
        <a href='/word_detail.php?id=20881' onmouseover="showToolTip(this, '偏正複句 piānzhèng fùjù', 'a subordindate complex sentence')" onmouseout="hideToolTip()">偏正复句</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout="hideToolTip()">中</a><a href='/word_detail.php?id=9803' onmouseover="showToolTip(this, '常見 chángjiàn', 'common')" onmouseout="hideToolTip()">常见</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=6091' onmouseover="showToolTip(this, '關聯 guānlián', 'related / linked / affiliated')" onmouseout="hideToolTip()">关联</a><a href='/word_detail.php?id=9274' onmouseover="showToolTip(this, '連詞 liáncí', 'conjunction')" onmouseout="hideToolTip()">连词</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" 
        onmouseout="hideToolTip()">有</a>：<a href='/word_detail.php?id=12957' onmouseover="showToolTip(this, '寧可 nìngkě', 'would rather / preferably')" onmouseout="hideToolTip()">宁可</a>、<a href='/word_detail.php?id=2076' onmouseover="showToolTip(this, '與其 yǔqí', 'it\'s better ... than ...')" 
        onmouseout="hideToolTip()">与其</a>、<a href='/word_detail.php?id=4617' onmouseover="showToolTip(this, 'jiù shì', 'even if / even')" onmouseout='hideToolTip()'>就是</a>、<a href='/word_detail.php?id=2684' onmouseover="showToolTip(this, 'jíshǐ', 'even if / even though')" onmouseout="hideToolTip()">即使</a>、<a href='/word_detail.php?id=12578' onmouseover="showToolTip(this, 'jiǎrú', 'if')" onmouseout="hideToolTip()">假如</a>、<a href='/word_detail.php?id=2661' onmouseover="showToolTip(this, 'rúguǒ', 'if / in case / in the event that')" onmouseout="hideToolTip()">如果</a>、<a href='/word_detail.php?id=10419' onmouseover="showToolTip(this, 'yàoshi', 'if')" onmouseout="hideToolTip()">要是</a>、<a href='/word_detail.php?id=4415' onmouseover="showToolTip(this, 'chúfēi', 'only if / only when / only in the case that')" onmouseout="hideToolTip()">除非</a>、<a href='/word_detail.php?id=8893' onmouseover="showToolTip(this, 'zhǐyǒu', 'only')" onmouseout="hideToolTip()">只有</a>、<a href='/word_detail.php?id=4559' onmouseover="showToolTip(this, '無論 wúlùn', 'no matter what / regardless of whether')" onmouseout="hideToolTip()">无论</a>、<a href='/word_detail.php?id=10506' onmouseover="showToolTip(this, '不論 bùlùn', 'whatever / regardless')" onmouseout="hideToolTip()">不论</a>、<a href='/word_detail.php?id=10504' onmouseover="showToolTip(this, 'bùguǎn', 'regardless of / no matter')" onmouseout="hideToolTip()">不管</a>、<a href='/word_detail.php?id=10750' onmouseover="showToolTip(this, 'jìrán', 'since / as / this being the case')" onmouseout="hideToolTip()">既然</a>、<a href='/word_detail.php?id=2192' onmouseover="showToolTip(this, '由於 yóuyú', 'due to / as a result of / because of / owing to')" onmouseout="hideToolTip()">由于</a>、<a href='/word_detail.php?id=1369' onmouseover="showToolTip(this, '因為 yīnwèi', 'because / owing to / on account of')" onmouseout="hideToolTip()">因为</a>、<a href='/word_detail.php?id=592' onmouseover="showToolTip(this, '儘管 jǐnguǎn', 'despite / although / even though')" onmouseout="hideToolTip()">尽管</a>、<a href='/word_detail.php?id=1180' onmouseover="showToolTip(this, '雖然 suīrán', 'although / even though')" onmouseout="hideToolTip()">虽然</a>、<a href='/word_detail.php?id=697' onmouseover="showToolTip(this, 'dànshì', 'but')" 
        onmouseout="hideToolTip()">但是</a>、<a href='/word_detail.php?id=20925' onmouseover="showToolTip(this, '為的是 wèideshì', 'for the sake of / for the purpose of')" onmouseout="hideToolTip()">为的是</a>、<a href='/word_detail.php?id=2106' onmouseover="showToolTip(this, 'yīncǐ', 'for that reason / therefore / for this reason')" onmouseout="hideToolTip()">因此</a>、<a href='/word_detail.php?id=4851' onmouseover="showToolTip(this, 'suǒyǐ', 'therefore / as a result / so')" 
        onmouseout="hideToolTip()">所以</a>。<a href='/word_detail.php?id=20881' onmouseover="showToolTip(this, '偏正複句 piānzhèng fùjù', 'a subordindate complex sentence')" onmouseout="hideToolTip()">偏正复句</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=20922' onmouseover="showToolTip(this, 'zhèngjù', 'main clause')" onmouseout="hideToolTip()">正句</a><a href='/word_detail.php?id=332' onmouseover="showToolTip(this, 'zhōng', 'middle / during')" onmouseout="hideToolTip()">中</a><a href='/word_detail.php?id=9803' onmouseover="showToolTip(this, '常見 chángjiàn', 'common')" onmouseout="hideToolTip()">常见</a><a href='/word_detail.php?id=273' onmouseover="showToolTip(this, 'de', 'possessive particle')" onmouseout="hideToolTip()">的</a><a href='/word_detail.php?id=6091' onmouseover="showToolTip(this, '關聯 guānlián', 'related / linked / affiliated')" onmouseout="hideToolTip()">关联</a><a href='/word_detail.php?id=9271' onmouseover="showToolTip(this, '副詞 fùcí', 'adverb')" onmouseout="hideToolTip()">副词</a><a href='/word_detail.php?id=398' onmouseover="showToolTip(this, 'yǒu', 'is / are / to have')" 
        onmouseout="hideToolTip()">有</a>：<a href='/word_detail.php?id=1164' onmouseover="showToolTip(this, '纔 cái', 'just / not until')" onmouseout="hideToolTip()">才</a>、<a href='/word_detail.php?id=902' onmouseover="showToolTip(this, 'jiù', 'right away / only / precisely')" onmouseout="hideToolTip()">就</a>、<a href='/word_detail.php?id=925' onmouseover="showToolTip(this, 'yě', 'also')" onmouseout="hideToolTip()">也</a>、<a href='/word_detail.php?id=757' onmouseover="showToolTip(this, 'dōu', 'all')" onmouseout="hideToolTip()">都</a>、<a href='/word_detail.php?id=1964' onmouseover="showToolTip(this, 'jí', ' promptly / right away')" onmouseout="hideToolTip()">即</a>、<a href='/word_detail.php?id=2814' onmouseover="showToolTip(this, 'fǎnér', 'instead / rather')" 
        onmouseout="hideToolTip()">反而</a>。
      </p>
      <p>
        Often encountered correlative conjunctions in subordindate complex sentences include: <a href='/word_detail.php?id=12957' onmouseover="showToolTip(this, '寧可 nìngkě', 'would rather / preferably')" onmouseout="hideToolTip()">宁可</a>、<a href='/word_detail.php?id=2076' onmouseover="showToolTip(this, '與其 yǔqí', 'it\'s better ... than ...')" 
        onmouseout="hideToolTip()">与其</a>、<a href='/word_detail.php?id=4617' onmouseover="showToolTip(this, 'jiù shì', 'even if / even')" onmouseout='hideToolTip()'>就是</a>、<a href='/word_detail.php?id=2684' onmouseover="showToolTip(this, 'jíshǐ', 'even if / even though')" onmouseout="hideToolTip()">即使</a>、<a href='/word_detail.php?id=12578' onmouseover="showToolTip(this, 'jiǎrú', 'if')" onmouseout="hideToolTip()">假如</a>、<a href='/word_detail.php?id=2661' onmouseover="showToolTip(this, 'rúguǒ', 'if / in case / in the event that')" onmouseout="hideToolTip()">如果</a>、<a href='/word_detail.php?id=10419' onmouseover="showToolTip(this, 'yàoshi', 'if')" onmouseout="hideToolTip()">要是</a>、<a href='/word_detail.php?id=4415' onmouseover="showToolTip(this, 'chúfēi', 'only if / only when / only in the case that')" onmouseout="hideToolTip()">除非</a>、<a href='/word_detail.php?id=8893' onmouseover="showToolTip(this, 'zhǐyǒu', 'only')" onmouseout="hideToolTip()">只有</a>、<a href='/word_detail.php?id=4559' onmouseover="showToolTip(this, '無論 wúlùn', 'no matter what / regardless of whether')" onmouseout="hideToolTip()">无论</a>、<a href='/word_detail.php?id=10506' onmouseover="showToolTip(this, '不論 bùlùn', 'whatever / regardless')" onmouseout="hideToolTip()">不论</a>、<a href='/word_detail.php?id=10504' onmouseover="showToolTip(this, 'bùguǎn', 'regardless of / no matter')" onmouseout="hideToolTip()">不管</a>、<a href='/word_detail.php?id=10750' onmouseover="showToolTip(this, 'jìrán', 'since / as / this being the case')" onmouseout="hideToolTip()">既然</a>、<a href='/word_detail.php?id=2192' onmouseover="showToolTip(this, '由於 yóuyú', 'due to / as a result of / because of / owing to')" onmouseout="hideToolTip()">由于</a>、<a href='/word_detail.php?id=1369' onmouseover="showToolTip(this, '因為 yīnwèi', 'because / owing to / on account of')" onmouseout="hideToolTip()">因为</a>、<a href='/word_detail.php?id=592' onmouseover="showToolTip(this, '儘管 jǐnguǎn', 'despite / although / even though')" onmouseout="hideToolTip()">尽管</a>、<a href='/word_detail.php?id=1180' onmouseover="showToolTip(this, '雖然 suīrán', 'although / even though')" onmouseout="hideToolTip()">虽然</a>、<a href='/word_detail.php?id=697' onmouseover="showToolTip(this, 'dànshì', 'but')" 
        onmouseout="hideToolTip()">但是</a>、<a href='/word_detail.php?id=20925' onmouseover="showToolTip(this, '為的是 wèideshì', 'for the sake of / for the purpose of')" onmouseout="hideToolTip()">为的是</a>、<a href='/word_detail.php?id=2106' onmouseover="showToolTip(this, 'yīncǐ', 'for that reason / therefore / for this reason')" onmouseout="hideToolTip()">因此</a>、and <a href='/word_detail.php?id=4851' onmouseover="showToolTip(this, 'suǒyǐ', 'therefore / as a result / so')" 
        onmouseout="hideToolTip()">所以</a>.
        Frequently encountered correlative adverbs in the main clauses of subordindate complex sentences include: <a href='/word_detail.php?id=1164' onmouseover="showToolTip(this, '纔 cái', 'just / not until')" onmouseout="hideToolTip()">才</a>、<a href='/word_detail.php?id=902' onmouseover="showToolTip(this, 'jiù', 'right away / only / precisely')" onmouseout="hideToolTip()">就</a>、<a href='/word_detail.php?id=925' onmouseover="showToolTip(this, 'yě', 'also')" onmouseout="hideToolTip()">也</a>、<a href='/word_detail.php?id=757' onmouseover="showToolTip(this, 'dōu', 'all')" onmouseout="hideToolTip()">都</a>、<a href='/word_detail.php?id=1964' onmouseover="showToolTip(this, 'jí', ' promptly / right away')" onmouseout="hideToolTip()">即</a>、<a href='/word_detail.php?id=2814' onmouseover="showToolTip(this, 'fǎnér', 'instead / rather')" 
        onmouseout="hideToolTip()">反而</a>。
      </p>
      <p>
        Next: <a href='grammar_comparison.php'>Expressing Comparison 表示比较</a>
      </p>
    </div>
  </body>
</html>
